### ISSUE TITLE
Add option to disable facades

### ISSUE THREAD

**Issue by SpaceToad** [BuildCraft/BuildCraft#1914]
See http://www.minecraftforum.net/topic/682920-172-buildcraft-nextgen-6016-builders-blueprints-pipes-quarry-auto-crafting-building-engines/page__st__20880#entry32394062

**Comment by 3jlowes** [comment]
Is there any way to blacklist certain facades? Or disable facades without having to not include BC silicon?

**Comment by Morpheus1101** [comment]
Only way i know of to "hide them" is using JEI hiding function, otherwise you could possibly look into using crafttweaker script

**Comment by AlexIIL** [comment]
Current versions of BuildCraft allow you to disable any item or block by changing the relevant option in "objects.cfg".

**Comment by AlexIIL** [comment]
(Although this can only disable facades as a whole - it's currently impossible to disable specific facades). Is there a reason why you want to disable certain facades?

**Comment by 3jlowes** [comment]
Well my idea was that I could disable the facade that aether 2 is making. With its block. 
https://github.com/BuildCraft/BuildCraft/issues/4142
"Block = aether:therastone_brick_decorative" is the block being referenced in the issue, but if aether 2 handles all their blocks in the same way, maybe adding all of their blocks to a facade blacklist would be nice to prevent the crash (if this is possible.) I know the issue comes from aether 2, but having a blacklist could be a work around as aether 2 has "got no answer as to whether a fix was in progress for this."

**Comment by AlexIIL** [comment]
Oh right ok. We're not going to add a way for players to disable facades that fail the preload checks as that code really needs to be fixed in aether 2.

**Comment by 3jlowes** [comment]
Alright thanks for your time and fast responses. Really appreciate it. Do you think it is an easy fix for the aether 2 team?

**Comment by AlexIIL** [comment]
Hopefully. However I don't know without looking unfortunately.

**Comment by A-gmaE-programmer** [comment]
I seem to be having the same problem but with vanilla minecraft for a facade that cannot even be obtained
Here is part of the crash log


net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Silicon (buildcraftsilicon)
Caused by: java.lang.IllegalStateException: Scanning facade states
    State = minecraft:double_stone_slab[seamless=true,variant=stone]
    Block = minecraft:double_stone_slab
    Stack = 1xtile.stoneSlab@0
    varying-properties: {
        PropertyBool{name=seamless, clazz=class java.lang.Boolean, values=[true, false]} = null
    }

**Comment by AlexIIL** [comment]
@A-gmaE-programmer You'll need to upload the full crash report to a [new issue](https://github.com/BuildCraft/BuildCraft/issues/new?assignees=&labels=auto%3A+crash&template=crash.md&title=Crash), as this isn't really the best place for it.
