### ISSUE TITLE
Builder causes lag

### ISSUE THREAD

**Issue by marcin212** [BuildCraft/BuildCraft#2129]
When I open builder my server have freeze and drop all players.

**Comment by mmermerkaya** [comment]
I have the same GUI lag problem. When I open the builder gui with a template in it, I get massive lag.

"Can't keep up! Did the system time change, or is the server overloaded? Running 17594ms behind, skipping 351 tick(s)"

**Comment by asiekierka** [comment]
@mmermerkaya - Does it only happen with templates or?

**Comment by mmermerkaya** [comment]
Actually I think I was mistaken. Same thing happened today with the filler. My guess is that it happens only when the machine has been waiting for a while. Both times I didn't have enough materials to complete the structure and had to gather for a while and leave the machine idle. I updated to 6.4.1 and the problem persists.

Thanks for your help.

**Comment by Hazado** [comment]
I have this issue when my builder runs out of materials and still has power. TPS drops to about 1.

**Comment by ruyanve** [comment]
I can confirm this, builder without materials lags sever to a halt.

Forge 1291
Buildraft 6.4.3

modlist: http://pastebin.com/tsCaNMnP

**Comment by asiekierka** [comment]
Found it!

**Comment by mmermerkaya** [comment]
Great, thanks!

**Comment by dogemanmcgee** [comment]
Sorry to open this again, but it's become a huge problem for me and it's annoying many people on the server I play on. Here's what happens: I start building a massive (200x200x150) build and if I decide to right click on my builder, everyone on the server gets a "timed out" error and the server is unresponsive for the next ~10 secs, depending on how long I kept the builder screen open. This also happens in single player but is much more detrimental in multiplayer. My best theory is that it's having trouble rendering such a big build, because the timeout scales down greatly when the build is smaller.

**Comment by AEnterprise** [comment]
@dogemanmcgee please open an new issue for this, also include mod versions, forge version, mc version and if possible a link to some profiling, a log might help as welll

a link to the blueprint to test might help as well unless you are using alot of mods in it
