### ISSUE TITLE
Quarry Stuck on water.

### ISSUE THREAD

**Issue by dark-skript** [BuildCraft/BuildCraft#2351]
Quarry can't go through water anymore.

Using build 657 from Jenkins.

Examples:
http://www.bravegaming.net/quarry_no_like_water_2.gif
http://www.bravegaming.net/quarry_no_like_water.gif

Thanks.

**Comment by asiekierka** [comment]
@TheJulianJES - He found a valid bug. While I usually scold people for using Jenkins builds, that's because often it diminishes the quality of the mod as perceived by the public.

He clearly marked that he was using a Jenkins build, implying awareness of what he is doing, and that's when I'm fine with it.

**Comment by TheJulianJES** [comment]
@asiekierka Okay!
