### ISSUE TITLE
Builder can be used to get free resources in worlds that were started as creative, even if the player is in survival

### ISSUE THREAD

**Issue by Sirithil** [BuildCraft/BuildCraft#2414]
I'm on survival, but the builder works without requiring the input of blocks. This has something to do with the fact I start my worlds on creative so I can fly around and find a place to start, but then switch to survival. It still says 'creative' in the world selection menu.

I confirmed this by starting a world on survival and switching to creative, making a quick test blueprint, and then putting the blueprint in a builder. Hypothesis confirmed -- this time it was asking for resources and would not run without them. Once supplied it ran properly and constructed my build.

Instead of looking at the world's gamemode, it should probably instead look at the current gamemode of the player that placed it.

**Comment by asiekierka** [comment]
No. The current gamemode is far more open to manipulation.

Why are you doing that? A far better way is to use Survival Mode with cheats on and change your gamemode around, OR just use NEI.

Won'tfix.

**Comment by Neamow** [comment]
That's really stupid, Asie. You should use the player gamemode, not the world gamemode. It took me so long to understand why the builder wasn't using up blocks even though I was in Survival. Just because I liked a world I happened to find during creative testing of the modpack, and changed immediately to Survival shouldn't mean the world is eternally in Creative anyway. Now I have to use NBTEditor to manually change the world gamemode to Survival so the thing works. I love the Builder, and it works beautifully, but this has to be fixed.
