### ISSUE TITLE
AutoWorkbench doesn't continue crafting

### ISSUE THREAD

**Issue by hea3ven** [BuildCraft/BuildCraft#2445]
The AutoWorkbench crafts only once and then stops even if it has space for more craft operations.

**Comment by asiekierka** [comment]
@immibis - You fiddled with the auto workbenches recently; could you confirm?

**Comment by MrKickkiller** [comment]
Can confirm this to be true; Even more, the workbench doesn't seem to be automatically distributing the items.

**Using: ** Buildcraft 6.3.4 with Buildcraft Compat 1.0.0
We first noticed the problem when connecting the Workbench to a BP tubes. It would simply stack all the items in the first slot and then continuing with the 2nd and 3rd slot etc....
Then we tried using a hopper on top of the workbench: Same behaviour.

Someone suggested it was caused by COFH, so I removed all COFH mods from my instance and tried again : No distribution / crafting

Proof that it doesn't distribute :http://gyazo.com/74f7fa92eebab21a07f3d523a33032a4
**By now it should have redistributed some items to the bottom row**
