### ISSUE TITLE
Openblock's Gravestone + Quarry.

### ISSUE THREAD

**Issue by Alexmaster50** [BuildCraft/BuildCraft#2472]
When I fell into my quarry, I died of fall damage.
My Openblock's grave spawned correctly, however upon being mined by the quarry non of the items were in the output chests of my quarry.
My piping is correct and it mined everything else perfectly.
I tested this 2 more times and it didnt output my items.

**Comment by boq** [comment]
Hi, OpenBlocks dev here. This is caused by [this](https://github.com/BuildCraft/BuildCraft/blob/6.3.x/common/buildcraft/factory/BlockMiner.java#L117) line.

On first glance, it looks needless (and even harmful) - TE is normally removed in `Block.breakBlock()` (called via `World.setBlockToAir`) and it should be available until then. So what's the story behind [this](https://github.com/BuildCraft/BuildCraft/commit/e4bf8981d7654f9942fe1862e8068e3d666a3d8a) commit?

**Comment by Alexmaster50** [comment]
I put it in both github report sections as I thought it maybe an integration bug of some sort. I didn't know which mod caused it to happen so I put it in both sections.

Is there anyway to blacklist graves from the quarry via my server's configs?
I'm not a coder in anyway so I have no idea what any of that line means or does.

**Comment by AEnterprise** [comment]
i remember that i used this quarry trick a once to get my stuff back afther dying in the deep dark, it wasn't the latest BC but it did work a while back so i'm guess that was indeed inteded behaviour that is now broken

**Comment by asiekierka** [comment]
Oh, huh. I forgot to fix this in 6.3.7, apparently.
