### ISSUE TITLE
BC pipes still have issues with TiCon smeltery

### ISSUE THREAD

**Issue by D3sman** [BuildCraft/BuildCraft#2631]
I'm playing Regrowth 7.4, after the recent fix.

My setup looks like this: http://i.imgur.com/kEQYHqR.png

I normally smelt a large amount of different ores that can't be alloyed, then activate the lever. Every once in a while I come back, and find that the ingot cast is partially full, the casting has stopped, and one of the metals has its quantity measured in nuggets.

**Comment by asiekierka** [comment]
Wait. What you mean is that the ingot cast is partially full *and* there is a metal left in the smeltery?

**Comment by D3sman** [comment]
Something like that. There are multiple metals left in the smeltery, because there is that stoppage in the ingot cast. I'm not sure about the metal in the cast itself, if some of that was lost or simply rerouted into the pipes or the smeltery etc.

The details are getting a little fuzzy after a while. Dealing with this multiple times is so annoying that I just switch to a redstone clock as soon as I can.

**Comment by AEnterprise** [comment]
i think i know the cause it's just your setup causing this, the ingot needs a few secs to become a solid item to be pulled out, in that time the next fluid get's extracted already, due to the fact that the table doesn't accept the liquid yet it (partially) bounces back up the pipe in to the smeltery

if there is nothing of that fluid remaining the bounced back fluid isn't the botom one and ends up on top of the list, resulting in part of the ingot being in the cast the rest in the smeltery

**Comment by immibis** [comment]
Possible fix: prevent wooden pipes from inserting into the side they extract from?

**Comment by asiekierka** [comment]
@immibis - That assumes that is the reason, however it's a good idea to do anyway.

**Comment by asiekierka** [comment]
I'm pretty sure this is not the case anymore.
