### ISSUE TITLE
Oil and Water springs not working v6.4.11

### ISSUE THREAD

**Issue by hehe3301** [BuildCraft/BuildCraft#2633]
Oil and water springs are not working in version 6.4.11

**Comment by adudney** [comment]
How are they not working? Can you provide extra description and screenshots? If it crashes, can you provide a crash log?

You can edit your original post to add information, you don't have to make a new comment.

**Comment by Zaflis** [comment]
They have been working even too well as far as i can tell, i have this in config

worldgen {
    B:oilSprings=true
    B:waterSpring=false
}

Water springs are still generated, as can be told after quarrying large areas to bedrock, and observing the random spring blocks. "Not working" part here is that it's ignoring the config where i'm trying to disable them.

**Comment by psxlover** [comment]
@Zaflis are you sure your world was generated before you changed the config? You should note that the Spring is not the water/oil source block but the bedrock block below it, and the config option doesn't affect whether or not water/oil will be generated but whether or not he special bedrock blocks will be generated.

**Comment by Zaflis** [comment]
Yes, i've played many recent worlds with same configs and i always keep my mods up to date. I've checked with Waila that the block indeed belongs to Buildcraft. Water springs generate the extra bedrock block, which became issue first time with turtle miner getting stuck, but since then mining with quarry or worldhole enderquarry. Removing them from world is difficult, when you need to remove each source block from surface to bedrock. With another config change pump can do it, but slowly.
