### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by pchard** [BuildCraft/BuildCraft#2723]
Log from the bottom of fml-client-latest.log:

http://pastebin.com/3xj2iSX3

I'm running on Linux 64bit with 8GB ram.
Whenever I join my server or my single player world, it goes up to max ram.

I have allocated 1GB, but yet it goes up to 6-7GB of RAM, and my computer freezes.

It happened right after I installed the latest version of Buildcraft.

Could this be a memory leak, perhaps?

**Comment by pchard** [comment]
Using 1.7.10

**Comment by AEnterprise** [comment]
not seeing anything BC related at all in that log, only openblocks errors

**Comment by pchard** [comment]
Let me put up the full log.

**Comment by Speiger** [comment]
@AEnterprise could that happen because of the Difference with the Forge API because it seems to be that happens because of the fluids.... Maybe Openblocks has still the old API and bc has the new one... Just thinking

**Comment by AEnterprise** [comment]
@Speiger i don't think so, it is possible they didn't update but i would expect it to crash then, eighter way it shouldn't be BC related as BC has nothing to do with openblocks, they don't have any specific integration

**Comment by Speiger** [comment]
@AEmterprise
it is sure that it is a Openblocks bug, but BC causes it to happen. That is a fact!
Maybe @asie should talk to the Openblocks guys and solve the problem.

**Comment by AEnterprise** [comment]
i think it should be reproted at the openblocks dev, they obviously have a check with warning build so they should be able to tell us what the exact problem and possible causes are

**Comment by Speiger** [comment]
My words xD Sorry for misstyping your name, Phone Keys are so small xD

**Comment by iTitus** [comment]
Pinging @boq and @mikeemoo here

**Comment by boq** [comment]
Hi,

Just to clarify:
- OpenBlocks uses only parts of pipe API - and they are fetched from Maven repo - so this is unrelated
- this warning occurs when `FluidRegistry.getFluidStack(fluid.getName(), ...)` returns null. Since we are iterating over `FluidRegistry.getRegisteredFluids()`, it looks like registration error
- I'm not sure who owns liquids `fluidpure`, `fluiddeath` and `fluxgoo`, but it's probably not BC
- if you can't find original mod author and make him fix his fluid registration, you can disable this part of code with config option `displayAllFluids`.

**Comment by Speiger** [comment]
That sounds more like Thaumcraft but he is right^^"

**Comment by johnneijzen** [comment]
It probable that is from forge fluid registering change.
