### ISSUE TITLE
Lava bucket can generate more energy in Stirling Engine than in Combust Engine

### ISSUE THREAD

**Issue by oldjunyi** [BuildCraft/BuildCraft#2731]
10 RF/t * 20000 ticks = 2 * 10^5 RF in Stirling Engine
20 RF/t * 6000 ticks = 1.2 * 10^5 RF in Combust Engine

Looks a bit weird. Maybe the lava bucket should be banned from burning in Stirling Engine.

**Comment by psxlover** [comment]
It doesn't seem weird at all to me.It just seems that combustion engine sacrifices efficiency for speed.

**Comment by LouisHutch** [comment]
Asie did say at one point that he wanted to remove the lava + water rf gen in a combustion engine. Anyway, blame spacetoad \o/ : https://github.com/BuildCraft/BuildCraft/issues/1955

**Comment by asiekierka** [comment]
Noticed this by accident: I'd preferably kill off the lava + water gen. It makes zero sense. Most of the past BC teams generally agree.

If you want lava power generation, you should consider making a separate engine - however, it is unwanted due to the issues of lag and balance both with BC's pumps and the nether's vast amounts of lava.
