### ISSUE TITLE
placing Galacticraft Sealed BC pipes causing internal server error

### ISSUE THREAD

**Issue by Faryzal2020** [BuildCraft/BuildCraft#2744]
error from latest.log : http://pastebin.com/FuWWizpZ

buildcraft version: 6.4.16
compat version: 6.4.2
galacticraft version: 3.0.11.333

**Comment by AEnterprise** [comment]
seems you are running a bukkit server, can you try to recreate this on a forge server?

**Comment by asiekierka** [comment]
Galacticraft is not checking for the presence of BuildCraftCompat, which overrides the TileGenericPipe registration.

**Comment by radfast** [comment]
*Note from the GC developers:*

Thanks to @asiekierka for identifying the issue, and thanks to all who spotted it and contributed to this issue report.

The issue has been fixed in Galacticraft versions 411 and later.  Earlier versions of Galacticraft must not use the "Sealed xxxx Pipe" blocks if BCCompat is loaded - sorry.

I apologise for the long time it has taken us to deal with this, I have taken time away from the project for personal reasons.

**Comment by asiekierka** [comment]
Better late than on another Minecraft version altogether. :-)
