### ISSUE TITLE
Found some errors

### ISSUE THREAD

**Issue by mimic2300** [BuildCraft/BuildCraft#2815]
hi, i dont know, if it is severity error or not, but in logs are those lines:

[Client thread/ERROR] [BuildCraft Additions/bcadditions]: CompatModule 'Framez' is missing a dependency: 'framez'! This module will not be loaded.

[Client thread/ERROR] [BuildCraft Additions/bcadditions]: CompatModule 'MineTweaker' is missing a dependency: 'MineTweaker3'! This module will not be loaded.

**Comment by Sandriell** [comment]
@mimic2300 I believe you need to update your Java to version 8.

**Comment by mimic2300** [comment]
i already use jdk 1.8.0_5

**Comment by Sandriell** [comment]
@mimic2300 Then ensure you are using that version. Check the beginning of the logs to see what version MC is using.

Should be something like "[17:44:56] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_25"

It could be another reason, but the only time I have seen errors like those two lines is when trying to start under Java7. And since those two lines are all you provided, its all I have to go one. :)

**Comment by mimic2300** [comment]
yeah.. MC use same version. This error does not cause the version of Java but mod: BuildcraftAdditions-1.7.10-2.1.4 (use BC 7.0.10)

**Comment by AEnterprise** [comment]
@mimic2300 you are on the wrong issue tracker, this is a error from my mod BCA not BC. Also this is not realy an error but an informative message, BCA has build in compatibility with those mods but as they are not pressent those features are dissabled and these messages can safely be ignored

**Comment by iTitus** [comment]
Yeah, this is not an incompatability or an error with your Java version.
We should move the logging level to INFO or something like that to make it more clear to users that this is no error.

**Comment by mimic2300** [comment]
ah.. ok.. sorry for spam on wrong the tracker :)
@iTitus yeah, info or warn would be better

**Comment by AEnterprise** [comment]
i'll change that up, no idea at all why @BigXplosion considered it an error

**Comment by BigXplosion** [comment]
#blame @iTitus
