### ISSUE TITLE
Wooden Kinesis Pipes not transfering the correct amount of energy?

### ISSUE THREAD

**Issue by estebes** [BuildCraft/BuildCraft#2933]
I have an engine producing 140 rf/t (http://i.imgur.com/yism9md.png). When using a wooden kinesis pipe it seems that the maximum transfered energy is 32 rf/t and not 320 (http://i.imgur.com/rtkYtMj.png). Using an emerald kinesis pipe everything works fine (http://i.imgur.com/nK1WN6m.png). The setup - http://i.imgur.com/5fhFUsQ.jpg 

Issue #2854 might be related to this

**Comment by asiekierka** [comment]
No idea why. Looks really strange. Any further notes?

**Comment by psxlover** [comment]
https://github.com/BuildCraft/BuildCraft/blob/6.5.x/common/buildcraft/transport/pipes/PipePowerWood.java#L49 does that 320 have anything to do?

**Comment by asiekierka** [comment]
Yes, that's where the maximum extraction speed is defined.

**Comment by estebes** [comment]
No idea why this happens but im using bc 7.0.17 and bc compat 7.0.9. I'll try older versions to see if it still happens

**Comment by estebes** [comment]
Tried older version of bc and bc compat and the issue remains. Maybe an issue with the rf api?

**Comment by asiekierka** [comment]
Doubtful. Check if the Creative Engine (@ 160 RF/t) transfers energy correctly. Use a Wrench to change its power output.

**Comment by estebes** [comment]
With buildcraft engines it works fine. Maybe it is a forestry problem

**Comment by asiekierka** [comment]
RailCraft (possibly Forestry too) sends an amount of energy then void it. RF consumers can cap the amount of energy received, like we do, meaning that anything above 320 RF per "push" is lost in our case. This is on @CovertJaguar to fix.

**Comment by CovertJaguar** [comment]
I believe that was an intentional design decision, as the alternative was randomly exploding engines.

**Comment by estebes** [comment]
It doesnt affect me too much since i dont have any other uses for emeralds but having a pipe that is capable of transfering 320 rf/t and not be able to use it cause that engine has some weird mechanics might be annoying for other people

**Comment by SandGrainOne** [comment]
Could you also report this to Forestry as a potencial issue with the Electrical Engine? I don't use IC2 so I have been unable to do any experiments on my own.

I've been testing a little bit with Creative engines and I see different results based on how many engines I have. 2 engines producing 320 RF each will reach the limit of a Quartz pipe. (The power turns red). 9 engines at 80 RF each on the other hand does not. 9 times 80 is 720 RF. 3 of the wooden pipes in this test simply stopped outputting power and even though the Trigger "Power Requested" was true and the redstone signal should start the engines, they refuse to run. (They start up to fill the buffer of the wooden pipe, but stops even though the redstone signal remain on.)

This might be a built in feature of the creative engine, but it is inconsistent with what I would consider expected behaviour.

**Comment by estebes** [comment]
Doesnt seem like a creative engine issue because on this particular problem that i posted the electrical engine also fills his own buffer and the wooden pipe buffer but the energy transferred remains limited to that ~33 rf/t value. The first time i noticed the problem was because the power requested trigger on the gate wasnt working and when i looked the engine was simply cooling down because the buffer was full.

**Comment by SandGrainOne** [comment]
Yeah, my comment about the creative engine was unrelated. I'll open a new issue for that when I have time. I didn't manage to get my point across anyway.

But back on topic. Do you have any other mods that might interfere here? Like BuildCraft Compat? Could you try without any such mod? 

It could also be a bug with the Electrical engine so raising an issue with the Forestry project could still be of interest.

**Comment by asiekierka** [comment]
Try BuildCraft 7.0.20.

**Comment by estebes** [comment]
Thanks asie. It is now "fixed". Requires you to replace the pipe but apart from that no problems

**Comment by asiekierka** [comment]
Oh, it does? I forgot about that... Oops.
