### ISSUE TITLE
A TileEntity type buildcraft.transport.TileGenericPipe has throw an exception trying to write state

### ISSUE THREAD

**Issue by Smalfinn** [BuildCraft/BuildCraft#2934]
fml-server-latest.log - http://paste.ubuntu.com/11973617/

Doesn't sound too major but should I be worried?

**Comment by asiekierka** [comment]
This is strange...

**Comment by Smalfinn** [comment]
THAT DOESN'T SOUND GOOD!

**Comment by Thog** [comment]
This error is a compatibility issue with DynmapForge. Dynmap calls the writeChunkToNBT method from AnvilChunkLoader who forces Tileentities to be written on a clean TagCompound. This is strange because they use to be able to save data like that on a NBT. Can you try to run your server without DynmapForge to test if something similar occurs?

**Comment by Smalfinn** [comment]
Clean installed the server without Dynmap and still throws the error

fml-server-latest.log - http://paste.ubuntu.com/11991883/

**Comment by asiekierka** [comment]
BuildCraftCompat doesn't like you. Quite literally.

**Comment by Smalfinn** [comment]
Okay well thanks for looking :)

Just FYI - it's a server running the 1.7.10 pack from technic http://www.technicpack.net/modpack/the-1710-pack.453902

Anything you need from me just ask ^_^

**Comment by AEnterprise** [comment]
hmm, is it possible that BC is passing the wrong class to forge then? BCC provides alternative, tweaked classes, i suspect the original classes are getting parsed to forge
