### ISSUE TITLE
Buildcraft Architect Table Crash

### ISSUE THREAD

**Issue by Ayrrow** [BuildCraft/BuildCraft#3073]
Crash to desktop when trying to create a blueprint of a forestry multifarm. 

Blueprint progress bar goes all the way to the end before crashing.

Latest versions of Forestry 4.0.8 and Buildcraft 6.1.7

http://paste.ee/p/cSUC8

**Comment by asiekierka** [comment]
Why closed?

**Comment by Ayrrow** [comment]
I figured out the problem. I'd thought I'd left the multifarm without one block so it could be copied. I hadn't.

**Comment by Corgano** [comment]
Isn't this still a bug? Just ran into this in 1.7.10 and it's driving me crazy. Why was it closed if it's still a feature?

**Comment by AEnterprise** [comment]
@Corgano can you make a new isse  if you can reproduce this and provide crashlog with steps to reproduce?

**Comment by Corgano** [comment]
I can't give you a crash log because the HDD I had this on has just failed this morning :/
I could consistently crash it in 1.7.10 by selecting an area with landmarks, placing any number of forestry multifarm blocks in it, and then putting in a blueprint. IT would fill up the progress arrow, and the server would crash before giving the completed blueprint. I tried removing all farm blocks, and the area saved successfully. Placing even one farmland block inside the area make the server crash when trying to save the blueprint.

I don't have the crash log, but i remember it having to do with the NBT saving. Perhaps the forestry block nbt was being saved improperly.

**Comment by Corgano** [comment]
Used curse to make a new 1.7.10 profile, with just forestry and buildcraft
1: place landmarks
2: select area
3: place architect table
4: place a farm block inside are
5: place blueprint in architect

Expected: Blueprint to save and pop out other side
Result: Game crashes https://pastebin.com/dr7Lmzpz

My post above was about a standalone server, but it also crashes single player.

**Comment by AEnterprise** [comment]
alright, thanks for the info and report, now it can be looked into

**Comment by Ayrrow** [comment]
I worked around this issue by leaving one block off the farm and then placing it later. I always assumed the architect couldnt copy multiblocks

**Comment by Corgano** [comment]
Given the trace it should work without. Let me test...
