### ISSUE TITLE
Robots using flux infused tools and weapons from Redstone Arsenal

### ISSUE THREAD

**Issue by Amelia-** [BuildCraft/BuildCraft#3097]
When I make my robots use flux infused tools the tools lose energy when the robot uses them but when the tools runs out of energy the robots will just keep using them without problems. They will even pick up tools with no energy from a chest if they don't have a tool yet and use them.

The sword and battlewrench are different, they do not lose energy when the robot strikes something with them.

These things make it so the robot can use the tools and weapons endlessly.

This happens with Buildcraft 7.1.12.

**Comment by Amelia-** [comment]
Buildcraft 7.1.13 changed something to this.
The axe and pickaxe make the robots break blocks really slow when they run out of power, however the robots still keep using them and do not bring them back to a place where they are allowed to unload.

The swords still don't use energy and the omniwrench used by leafcutter robots as shears does not slow down when out of power.

**Comment by asiekierka** [comment]
Should robots just use their own power on flux infused tools?

**Comment by Amelia-** [comment]
That sounds like a good idea to me. I'm not sure if the 25000 RF they have is a little low for tools that use 200 RF per use but on the other side perhaps that balances out the fact that you do not have to repair, enchant or make new tools for them.
They will get 100 uses out of the tool before they go back to recharge not counting their own power use (I don't really know how much power the robots use for themselves).

If the unbreaking enchant works on the tools when the robot uses them you can get it down to 80 RF per use and that gives them 250 uses out of the tool without counting the robot's own power use.

**Comment by SandGrainOne** [comment]
I think robots should have their own tools instead of constantly trying to support new tools from new mods all the time. I think it is also easier for players to accept that a new "magic pick using fluffydust absorbed by swimming in lava" for some reason doesn't work when not even vanilla wood tools can be used.

I even think we can go as far as to force the creation of a tools factory if a player want to have long term automated systems using Robots. This means low durability and cheap materials. The robots would need to recharge from time to time anyway. Why not also do a tool switch at the same time.

**Comment by AEnterprise** [comment]
old issue, i sugest this is closed and we see what heapens with BC 8.0 as we're a few MC versions ahead, alot of things changed in both BC and other mods so this is eighter fixed or someone can open a new issue if it is a problem

**Comment by AlexIIL** [comment]
Yeah I'm likely going with @SandGrainOne 's suggestion here for BC 8.
