### ISSUE TITLE
Review my BuildCraft 8.0 ideas

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#3113]
Here's my notes so you can use them for the future: https://docs.google.com/document/d/1HdreXCsyPzzfTJ2xPtUNX_pwweS3SfUPfskM9YDS9-Q/edit

**Comment by TheAndrey** [comment]
Correct lags in the mod better.

**Comment by asiekierka** [comment]
@TheAndrey If the issue is on the side of plugins, we're not going to fix them. And if removing a feature means players suffer, we're not going to do that. And if you're going to use terrible hacks to fast-forward events to Bukkit, just add another terrible hack to remove BlockBreakEvents - it's BlockUtils.isBlockBreakCanceled(), or something.

Put pressure on the plugins which are lagigng your BlockBreakEvent handling, or KCauldron if its wrapper is too slow.

**Comment by XFactHD** [comment]
@TheAndrey this would automatically come with a rewrite of that size, especially because people are learning from faults.

**Comment by asiekierka** [comment]
@XFactHD - He means one specific lag issue, one which only manifests itself with a highly specific combination of Bukkit plugins and one which "fixing" would negatively implact everyone *not* using Cauldron. See https://github.com/BuildCraft/BuildCraft/issues/3109

**Comment by Kubuxu** [comment]
and many using it.

**Comment by XFactHD** [comment]
I know but other lag issues are fixed through rewrites. And if I recall correctly, BC gave more than one good example of that kind.

**Comment by RufusStark** [comment]
"Remove the Valves. They’re a terrible hack."

ouch. ;)

Actually, I wrote that with the intention of nudging along the idea that pipes should be "dumb" objects and all "intelligent" functions like filtering, switching/valving, etc. would be moved to gates or some other attachment. Seems like that's part of what you're suggesting, so that's good.

**Comment by asiekierka** [comment]
Dynamic switchin of this kind should not exist. Item and fluid pipes have iron pipes with controllable direction, and power never had one by explicit design.

**Comment by RufusStark** [comment]
Wait, you mean dynamic switching just for kinesis pipes, right? I added valve actions for kinesis pipes at SpaceToad's request for "consistency's sake" and because it was often requested by players. For that matter, SpaceToad had already added the 'open' and 'close' actions to gates on all pipes (including kinesis). I just added the side parameter and input/output actions. Originally I thought valves should only be valid on fluid pipes (thus the name). Due to the mechanics of fluid pipes, the limited flow rate of iron pipes, and most importantly the lack of a single input/multiple output fluid pipe, a lot of fluid transport tasks were effectively impossible. Valve actions provided a mechanism to rectify that situation. And, like I said, most of the "intelligent" or dynamic functions were being moved out of the pipes themselves already. That process continued with things like lens and filters, and unless I misunderstood, you suggested the same in regards to lapis and daizuli pipes. 

I don't really understand what you mean by radical changes. Adding fluid flow control actions to gates hardly seems radical compared to, say, programmable robots. If you mean that just in general, I'm kind of torn. On the one hand, I think there's a lot of aspects of BuildCraft that could be improved with a major design overhaul of both code and some game concepts. On the other, doing that would likely not only break compatibility, but perhaps more importantly it would break continuity within BuildCraft itself. From that perspective, it would probably make more sense to just write a different mod.

**Comment by asiekierka** [comment]
>the limited flow rate of iron [fluid] pipes

I admit, we never found a good solution for that.

>a single input/multiple output fluid pipe

You just attach the iron pipe (acting as a diode) to another fluid pipe. Woo!

>From that perspective, it would probably make more sense to just write a different mod. 

Now you understand why I left.

**Comment by RufusStark** [comment]
> > a single input/multiple output fluid pipe

> You just attach the iron pipe (acting as a diode) to another fluid pipe. Woo!

That's exactly what I used to do, but it never really worked quite right (again due to flow mechanics and limited flow rate), and talk about a hack. 

>> From that perspective, it would probably make more sense to just write a different mod.

>  Now you understand why I left.

Indeed, that seemed fairly evident. I do hope someone with your commitment takes up the BC reins.

**Comment by EvilCborg** [comment]
There are two kinds of pipes that I really want.
The first is a paint version of the diamond pipe witch paints items different colors  instead of routing them into different directions,
The second is a round robin version of the Lapis Pipe witch paint the first pile go through it red,the second green,ect.
These two can be achieved using currently available pipes in conjunction with gates but it will be very tricky and controling the speed is hard and it makes the overall transport speed very slow.

**Comment by AEnterprise** [comment]
are these idea's still up for review or planned for 8.0? if not should be closed
