### ISSUE TITLE
Compatibility problem with EnderIO

### ISSUE THREAD

**Issue by cqjjjzr** [BuildCraft/BuildCraft#3146]
Hi there.
I'm played on a client that installed EnderIO and BuildCraft. But when I tried to use Architect table to record my factory into blueprint, I found a problem: When I use survival mode, the pipe block and EIO machines are all disappeared. And I use creative mode, the items in some machines are still disappeared. All pipe block in EIO was detected as "Conduit Connector.", like the problem that occurred at old version of NEI & waila at Buildcraft.
I hope the problem canbe resolved. if you need more info, ask me.
sincerely.

**Comment by Nosnamreh** [comment]
Hi there!

I've bumped into this problem a bit myself. I want to say Builders can't place down tile entities, but I do remember it placing furnaces and crafting tables just fine. I'm really not entirely sure, so the only solution I can offer is to make a blueprint of the empty factory, without any machines or pipes or wires inside of it. It's not perfect, but it's better than doing it all by hand.

**Comment by AEnterprise** [comment]
odd that this issue was missed and not replied to, let me rectify that:

by default the architect table ignores ALL TE's EXCEPT those where explicit support has been added for (BC itself added that for all vanilla TE's, BC compat adds for some other mods), for EIO machines support needs to be added to eighter EIO itself or BC compat

this is to prevent the massive dupe bugs we encountered earlier when the system was using a blacklist instead of a whitelist (blacklist aproach was impossible to keep track and find them all)
