### ISSUE TITLE
[Suggestion] Automatic Workbench upgrade-slot

### ISSUE THREAD

**Issue by accessdenied0** [BuildCraft/BuildCraft#3175]
Hello BuildCraft-Team,

I recently got the idea of a possibility to upgrade the Automatic Workbench. My idea was to add a "Gear-slot" and depend which Gear you insert in this slot, the Workbench works faster -or slower-.
Speed-ratios could be something like:
* Wood: 0.5
* Stone: 1.0
* Iron: 1.5
* Gold: 2.0
* Diamond: 3.0
Working-speed.

I would love to hear what you guys think about. (I'm sorry if there is anything planed already, if so, close this immediately.) 

access_denied

**Comment by AEnterprise** [comment]
sugestions to speed up the workbench have been made in the past and not implemented, there is the laserpowered version that you can use instead if you wana get faster crafting

**Comment by accessdenied0** [comment]
@AEnterprise, 

I'm sure about this. But the way how it could made, is in my opinion very interesting. Besides... you may correct me but the Laser-Workbench is outdated and no longer craft able.

access_denied

**Comment by AlexIIL** [comment]
Yes the Laser Crafting Table is not craraftable in 7.1.14. Its not a bad idea actually, I will add it to my BC 8 idea doc :)

If this does get added the numbers will probably be different. One thing I am wondering though, do you have any reasoning for having a slow down? And is there a reason why stone goes at a speed of 1.0? I'm assuming you mean these as a multiplier, but I would be interested if I'm wrong :)

**Comment by dj3520** [comment]
Question. I build a stone version. Now I want a faster one. Can I upgrade
my existing one or do I have to craft a new one?

**Comment by AlexIIL** [comment]
I'm assuming its a slot in the gui that you can place a gear into- so you can change it without needing to break the block.

**Comment by dj3520** [comment]
Hmm. Perhaps a new item. Currently the bench requires two gears, so that
and something else. Could have durability as a motivator towards the
recipie packer and stamping table setup.

**Comment by accessdenied0** [comment]
@AlexIIL,

I*m happy you like that concept. I'm thinking for the wooden-ratio (0.5) maybe for extreme slow recipes to reduce the ticking of the entity. The stone-gear-ratio I just wrote it down for completion maybe It just works with a gear at all. (Because Stone Gears aren't that expensive).

access_denied

**Comment by LuigiHutch** [comment]
I would say that the gears would only last a certain amount of 'cycles' and it only be able to hold 1 gear at a time. 

If the gears have a 'durability', I think all the gears should last the same amount of time so it's only the speed changes so a diamond gear isn't the very best for every situation.

Also giving gears durability will mean that it will have to be automated or manually maintained so it cannot be just placed and forgotten if it has a diamond gear in for example.

Question: Should you be able to automatically insert gears into the auto-workbench?

If so this could mean that people just have a hopper feeding into it with a bunch of gears in and then just forget about it.

**Comment by AlexIIL** [comment]
I'm personally not too happy with the idea of durability for automated things, especially since you are already able to insert any item into the crafting table and it could be easy to confuse which place you wanted it to go...

I also don't really like the idea of a perfect upgrade path- I want there to be a difference between all the gears (so they change the way it operates in some way).

On a side note the packager and stamping table will be getting changes (I'm not sure what exactly yet) and I've been thinking of making some recipes take longer to craft than others for balance (So you can pump out sticks out at a decent rate) but crafting complex recipes would take longer. Kinda how factorio works for this.

**Comment by AEnterprise** [comment]
maybe make it so that the gears only modify the speed a little bit and instead allow for more complex recipes?

**Comment by dj3520** [comment]
Perhaps iron/gold or above is required for recipes including more than one
item in a slot.
Maybe diamond takes as long but makes two items at once.

**Comment by SandGrainOne** [comment]
Please consider adding a durability to upgrades. The upgrades can be super cheap, but there should be a downside to an upgrade system. 

There should always be a trade between adding more machines and simply upgrading. Possible choices the player should have when designing a system:
 1. Use more machines (eg 3) to increase the speed of the system (eg 3 times)
 2. Upgrade one machine, but deal with some level of maintainance that can be automated.

Very few other options work very well. "Consume more power" is too easy to deal with. Crafting cost, even fairly expensive stuff like diamonds, are in most cases a non-issue for most players

I have never felt the need to automate the crafting of gears, but if my machines slowly used them up to work faster, then I would almost consider myself forced to do so. The important part here is that everything related to the maintainance can be automated.

**Comment by dj3520** [comment]
the issue with making the gears have durability is that they're crafting
items for a lot of things. I'd imagine it would be easier to make a new
item that has durability and cost a gear or two. Plus this item could have
a tooltip that explains its effect on the crafting process.

**Comment by AlexIIL** [comment]
If they had durability they would be seperate items rather than normal gears, that re not used in any (normal) crafting recipe

**Comment by dj3520** [comment]
So a gear with and without would be two different items? Without a way to
distinguish between the two that would confuse players who weren't aware
beforehand. A different item entirely is what I'm thinking, the equivalent
of a "crafting core" that for now only has use in the workbench. Having
durability also allows the repair mechanic to come into play, where
durability can be restored via combining two "worn" items into one, or
using the type's raw material and xp in an anvil. Due to the fact this
mirrors vanilla, nearly all players would recognize it.

**Comment by LuigiHutch** [comment]
Why not continue using gears, but instead of using actual durability, have a progress bar in the auto workbench GUI instead. This progress bar will show the 'durability' of the gear without actually giving the gears durability.
So it will start full when a gear is inserted and every time the auto workbench completes a craft, the progress bar decreases and when the progress bar becomes empty, the gear inside the auto workbench get destroyed. Similar to the progress bar in the forestry centrifuge but it indicates the state of the gear instead.

This could mean that people could take out the gear and reinsert it to give it full durability again, but as long as they can't be automatically pulled out. This will require manual interaction which will deter the user from doing this significantly.

**Comment by Kubuxu** [comment]
Do we really need that upgrade?

There is simple way: autoworkbench and there is tough but much faster way: packagers.

IMHO there is no need for tiered upgrades.

**Comment by AlexIIL** [comment]
It was never going to be a direct tiered upgrade system where diamond > wood

**Comment by LuigiHutch** [comment]
TBH: the only use for a packager and stamping system is for non-stackables. By the time a package is: pulled out of a packager into a stamping table, processed and then extracted to a destination; a auto workbench has competed its craft with plenty of time to spare :/

**Comment by AlexIIL** [comment]
Oh and it requires a constant stream of paper. And the output for a lot of recipes is in the same place...

**Comment by AlexIIL** [comment]
I'm starting to like the idea of making the upgrades a separate block...

**Comment by dj3520** [comment]
Besides the paper, which could be solved by having a robot sugar farm and
using the package manager to make more paper, one benefit of the stamping
machine is that you could request a craft from multiple locations, then
pipe it to one lazer room. Then it could be piped to an output chest for
pickup later.

**Comment by ThatGamerBlue** [comment]
How about we just make the Auto-Workbench instant? Like it used to be. When it was good.

**Comment by AlexIIL** [comment]
@ThatGamerBlue Nothing automated will ever be instant in BuildCraft as it just breaks the balance.

**Comment by dj3520** [comment]
And it would ruin the stamping machine's purpose.

**Comment by AEnterprise** [comment]
is this going to get implemented? if not should be closed

**Comment by AlexIIL** [comment]
I never found a good way to implement this for BC, so no I don't think BC will be getting upgrades.
