### ISSUE TITLE
[Question]Stirling Engine is the new Black

### ISSUE THREAD

**Issue by Gman-Nuggettes** [BuildCraft/BuildCraft#3192]
I have a stirling engine in my 1.7.10 world and i was running it constantly for a while (*20ish hours) and it turned black and started smoking. Can anyone tell me what this is? How do i prevent it? Is this a thing i can fix with gates?

**Comment by dj3520** [comment]
Overheated. Break and place again. Use gates to make sure the engine
doesn't reach "red state." Pumping water in combustion engines cools them,
meaning you shouldn't have a problem.

**Comment by XFactHD** [comment]
As far as I know you can't cool a Stirling engine with water.

**Comment by SandGrainOne** [comment]
Engines heat up and break down (turns black) if they have problems getting rid of the power they produce. The Stirling engine make a measly 10 RF/t, but if it is connected to a Pump or another machine that use less than 10 RF/t, then power will slowly build up and break the engine.

On trick is to create a system that would regulate power production to the power consumption.

Another trick is to create a system that simply detects when the engine turns yellow/red and turn it off before it breaks down. Though this might force the engine off at a time when you actually need power so not the best option.

In both systems you should have kinesis pipes between the engine and the machine so that you have something to place the gate(s) on.

**Comment by AEnterprise** [comment]
also if an engine overheats and turns black hit it with a wrench to fix the engine
