### ISSUE TITLE
[7.2.0-pre9][Cross-mod] java.lang.IllegalArgumentException: Empty string not allowed

### ISSUE THREAD

**Issue by iarspider** [BuildCraft/BuildCraft#3199]
Placing a quartz kinesis pipe with Actually Addons' Placer causes crash: http://pastebin.com/fdFUBVXu

The idea was to use a combination of breaker and placer (both from Actually Addons) to switch quarry on or off based on how full the chest it output to is.

**Comment by AlexIIL** [comment]
Thanks! There is a really odd issue with pipes atm where they don't know what they are in some situations, so that's a reliable way to reproduce it. One question though: does this happen with pre10? I released it on the forums here: http://www.mod-buildcraft.com/forums/showthread.php?tid=1853&pid=18223#pid18223 (just incase you got BC from an alternate source).

As a side note: there is a gate conditional that lets you turn a quarry on and off based off of some conditionals (I have no idea what ActuallyAdditions offers in terms of these, but just so you know that the gate on/off does work without crashing your game).

![screenshot from 2016-02-05 19 45 42](https://cloud.githubusercontent.com/assets/3751138/12857271/1fde42ac-cc41-11e5-9542-d1893b1bcc8b.png)

**Comment by iarspider** [comment]
Didn't even know quarries had gate actions! Will also test this with pre10.

Note to self: subscribe to that thread. [NEM](https://bot.notenoughmods.com/1.8.9.html) is unreliable.

**Comment by AlexIIL** [comment]
I'm not entirely sure how reliable BC forum thread subscriptions are, so I have a twitter where I pretty much only post releases (https://twitter.com/AlexIIL). I occasionally post spoilers but I will never fill up your news-feed with tweets :)

**Comment by iarspider** [comment]
Ah, the twitter is even better. And just noticed that I've used the wrong issue tracker - oops...

**Comment by AlexIIL** [comment]
:P No-one seems to know, especially with BC being available from places other than the forums. Soon issues will move back to this repo though.

**Comment by iarspider** [comment]
Just tested the same setup (with placer/breaker) with pre10. 

Good news: the game didn't crash. 

Not so good news: the pipe didn't get placed, but "something" (an invisible unbreakable nothing) was placed, and there seems to be no in-game way to remove that "something:
![Imgur](http://i.imgur.com/9WkqdBO.png)

**Comment by AlexIIL** [comment]
Ah. Try reloading the world? (Also is there anything in the log)

**Comment by iarspider** [comment]
This part of log seems to be the interesting one: http://pastebin.com/baMxwbyd

The "something" thing survived save-load.

**Comment by n00b7** [comment]
i saw this in there it looks like tileentity error:

 at de.ellpeck.actuallyadditions.mod.util.WorldUtil.breakBlockAtSide(WorldUtil.java:50)
    at de.ellpeck.actuallyadditions.mod.util.WorldUtil.breakBlockAtSide(WorldUtil.java:44)
    at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.doWork(TileEntityBreaker.java:92)
    at de.ellpeck.actuallyadditions.mod.tile.TileEntityBreaker.updateEntity(TileEntityBreaker.java:62)
    at de.ellpeck.actuallyadditions.mod.tile.TileEntityBase.func_73660_a(TileEntityBase.java:141)

**Comment by AEnterprise** [comment]
@n00b7 that has nothing to do with the crash or BC, that is another mod that has a block breaker, the crash heapens on placing/breaking a pipe with that mod but the final crash heapens later on BC's side
