### ISSUE TITLE
BC 7.2.5: Stacking Map Locations

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3295]
If you've a stack of map locations selected and right click anything all of these maps will get the same location information but they keep stacked until you try to place them to another slot where you can't stack the items anymore.

I assume the locations should work the same as the buckets means once you "fill" your map location it becomes "unstacked" and placed to a free slot (or drops).

The other thing i saw was when crafting several Map Locations at once (by shift click on the result) they don't seem to go into one stack directly but instead temporarily place in different slots before being stacked somehow automatically. This last point is not really a bug but you can see it and it looks somewhat weird.

**Comment by rapus95** [comment]
I'd rather consider it as a bug if you grab a stack of "used" map locations and can#t place them all in your inventory again

**Comment by AlexIIL** [comment]
From now on I guess all bugfixes are considered enhancements :P

**Comment by asiekierka** [comment]
@AlexIIL I consider "I assume the locations should work the same as the buckets means once you "fill" your map location it becomes "unstacked" and placed to a free slot (or drops)." as an enhancement, not a bugfix - it's adding a codepath, not fixing a codepath.

**Comment by AlexIIL** [comment]
Its more that you should never be able have multiple map locations that are stacked. The bug is that you can break this in normal play. Either that or you are able to stack similar map locations, which is not the case.

It doesn't matter if I need to add, remove or fix existing code as the only thing I consider when classifying something is its behaviour when compiled- a player doesn't care how it works internally.

I guess it comes down to if you consider breaking a spec by just not implementing code a "bug" or an "optional enhancement" (Say if I made an empty class ListABC<T> which implements List<T>, and just left all the methods empty- is it an enhancement to make it work or a bug that it doesn't work?)

**Comment by AlexIIL** [comment]
Wow apparently there is a lot of debate around on this. I'll drop it then :P

**Comment by AlexIIL** [comment]
I have been able to reproduce the bug with crafting however I'm not quite sure what causes it so I'm going to leave it for now.

**Comment by iTitus** [comment]
Different max stack sizes on client and server? Maybe caused by the NBT sync?

**Comment by AlexIIL** [comment]
The stack size check only depends on the item damage which should be syncing properly with the item itself. I want to check it out in a debugger properly before coming to a conclusion.

**Comment by rapus95** [comment]
Maybe you need to overwrite the deprecated `getMaxStackSize()` instead of the ItemStack version since `net.minecraft.inventory.Container.computeStackSize(...)` doesn't use the argument version. Either way that probably is a bug in forge since why introduce a new argument-based version if you don't use it...
