### ISSUE TITLE
auto workbench doesnt start building until player opens up its GUI

### ISSUE THREAD

**Issue by neuroaktivo** [BuildCraft/BuildCraft#3307]
auto workbench has all ingredients in but doesnt start building until player opens up the auto workbench GUI.happening to several autoworkbenches. they seemed to work fine until this last part i built. doesnt make much sense.

**Comment by neuroaktivo** [comment]
running a server mc1.8.9 ,bc 1.2.5 beta, doing ic2 recipes

**Comment by neuroaktivo** [comment]
i've noticed it happens when it runs out of ingredients to continue crafting, then when materials arrive and has enough to build it doenst start building again.

**Comment by rapus95** [comment]
I encountered this right now aswell. Put a stack of diamonds into it (using a pipe system) for transforming it to blocks. Now i wanted to see whether all stuff arrived at its chest but when i opened the chest it still was empty... So i looked for the problem and once i opened the workbench i saw a nice bunch of diamonds that started transforming right in that moment...

**Comment by rapus95** [comment]
It really breaks any kind of automated tree farm and since there is no space for lasers next to them there is not even a workaround :/

**Comment by AlexIIL** [comment]
Sorry, should have switched the label earlier

**Comment by oitsjustjose** [comment]
Yep, also just discovered this bug myself on my server making scrap-boxes in it D:

**Comment by rapus95** [comment]
I don't want to be impatient or impolite but since there are no news regarding any type of hotfix a friend of mine dug into it and found https://github.com/BuildCraft/BuildCraft/blob/7.2.x/common/buildcraft/factory/TileAutoWorkbench.java#L328 to be the problem since the flag is never set to false again, neither manually nor by scheduledCacheRebuild=true (when insertion happens automated). These flags are only triggered when the craftMatrix changed but not if the inputInventory changed.
Thus when items are inserted by a pipe it won't start crafting on its own (since it still thinks it's jammed).
As it seems a possible fix would be to add a scheduledCacheRebuild=true at the end of all setSlotContent methods.

Looking forward to a 7.2.7 Hotfix for making the worlds run automated again :)

**Comment by AlexIIL** [comment]
@rapus95 I don't have a problem with asking for fixes, especially if you find the bug for me :)

**Comment by rapus95** [comment]
@AlexIIL do you plan to release a new version/hotfix with this being solved? (7.2.7 beta) or do we have to fix more problems first? :D

**Comment by AlexIIL** [comment]
Its been (nearly) a month, I'm going to try to get a few more problems fixed before (hopdefully) releasing tomorrow.

**Comment by belathus** [comment]
I am still having a similar problem in 7.2.7. I am using a hopper to pull out a pickaxe to insert into a Progressive Automation miner, but the auto-workbench freezes everytime I walk away from it. As in, it literally crafts one item after I close the GUI then stops, not even filling the hopper. It restarts the moment I open the GUI, though. I am not inserting items at all aside from manually, as just putting a single stack of cobble and sticks can last a pretty long time in a PA miner.

**Comment by AlexIIL** [comment]
@belathus Looks like I only half fixed the problem :p

**Comment by rapus95** [comment]
@AlexIIL you already found the problem? If not, we assume, it's because non-stackable items jam faster than they get extracted. So you need the same event at extraction :)

**Comment by asiekierka** [comment]
I'm getting reports that this issue also affects 1.7.10. Could you backport this, @AlexIIL ?

**Comment by AlexIIL** [comment]
I'm looking into it, but it works a little differently in 7.1.x so don't expect anything soon :(
