### ISSUE TITLE
Builder - provide bookshelfs directly

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3332]
Why the builder requests books (and wood) instead of bookshelfs?

And are there any reasons why the builder won't place item frames (with items in it)?

**Comment by AlexIIL** [comment]
It requests wood? From my tests it only seems to require books. (Tested with a new blueprint in 7.2.x dev)

**Comment by rapus95** [comment]
You're right; I did some miscalculation...
What about the item frames?

**Comment by AlexIIL** [comment]
Support hasn't been added for them yet

**Comment by rapus95** [comment]
Why don't you change the code so that the machine just expects the very exact block as it is found in the recipe? 
For items like item frames (once implemented) and torches and flowers it'd be nice if these were not placed before the block they are planned to be attached to

**Comment by AlexIIL** [comment]
Yeah ok thats dumb as stone requires cobblestone rather than actual stone. I don't even want to know how badly you could exploit this with enchants.

And torch placement is broken. WHEN DID THAT HAPPEN :(

**Comment by LuigiHutch** [comment]
Tested In BC 7.2.6:
Can confirm the builder requires books instead of bookselfs and cobble instead of smooth stone>
I was unable to confirm that builder was unable to place item frames as it was able to place item frames for me:
![2016-05-12_15 45 52](https://cloud.githubusercontent.com/assets/9326429/15218814/6cb41c00-1859-11e6-8d0b-ca5065b3526e.png)
![2016-05-12_15 45 59](https://cloud.githubusercontent.com/assets/9326429/15218815/70276784-1859-11e6-9c64-8d1e7d1ca0d9.png)

The builder was also able to place torches for me:
![2016-05-12_15 48 27](https://cloud.githubusercontent.com/assets/9326429/15218858/9a65efac-1859-11e6-9a30-a9dfe5a3ca14.png)
![2016-05-12_15 48 32](https://cloud.githubusercontent.com/assets/9326429/15218859/9a66df0c-1859-11e6-9b0c-e060e5ac53d1.png)

**Comment by AlexIIL** [comment]
Were the wooden planks there before you started the torch blueprint?

**Comment by LuigiHutch** [comment]
ah, yes they were :/

**Comment by chemdork123** [comment]
@AlexIIL from @rapus95 comment:

> For items like item frames (once implemented) and torches and flowers it'd be nice if these were not placed before the block they are planned to be attached to

The same also applies to wooden trapdoors.  I was using them in a blueprint before and they are placed before the blocks they are attached to...

**Comment by AEnterprise** [comment]
the builder should definatly use the block in the world instead of it's drops, there could be an override registry where substitutions could be registered for custom itemstacks needed to place special blocks

**Comment by AlexIIL** [comment]
This is most likely going to be fixed for 8.0.x
