### ISSUE TITLE
[1.7.14] onNeighborChange/getTileEntity can enter a callback loop

### ISSUE THREAD

**Issue by RomanHargrave** [BuildCraft/BuildCraft#3378]
I'm reporting this ***on behalf of a user*** experiencing problems, so I'll try to give as much detail as possible.

User Environment:

* Windows 7 

* Java 1.8 Update 92, 32-Bit

* BC 1.7.14

* Using all mods included in Tekkit Legends 1.1.1

Here's an excerpt from the stack trace that includes the repeating calls:

```
[B#347]     at buildcraft.transport.BlockGenericPipe.onNeighborChange(BlockGenericPipe.java:555)
[B#347]     at net.minecraft.world.World.func_147453_f(World.java:3875)
[B#347]     at net.minecraft.world.World.func_147455_a(World.java:2603)
[B#347]     at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
[B#347]     at net.minecraft.world.World.func_147438_o(World.java:2540)
[B#347]     at buildcraft.transport.BlockGenericPipe.onNeighborChange(BlockGenericPipe.java:555)
```

I have a suspicion that the frame count is exceeding the instruction pointer size supported by a 32-Bit JVM but I have no idea if that's the case as I am not well-acquainted with JVM intricacies.

I myself am not affected by this, and am using a 64-Bit JVM 1.8 Update 66 on Linux 4.4.

**Comment by AEnterprise** [comment]
i guess you mean BC version 7.1.14, can he upgrade to the latest version and see if it heapens again?
how often does this come up in the log? if it's often can he check for any pipes that are next to something like a cobblegen or machines that indicate on/off states and see if the error goes away when breaking. If he can find the pipe that is causing it a picture of the setup might also help

if it still heapens in the latest version (7.1.17) can you give a new trace (and maybe log)? There have been changes to that class since that version so the line number number is incorrect

i suspect it is this line (https://github.com/BuildCraft/BuildCraft/blob/7.1.x/common/buildcraft/transport/BlockGenericPipe.java#L554) so most likely another mod is calling that function incorrectly

**Comment by RomanHargrave** [comment]
@AEnterprise This is a fatal client error. It occurs in or near a chunk that I built and have no issues with. Not sure which pipe setup is causing issues, though. Unfortunately, the server enforces mod versions (and I can't change that), so I can't do much in the way of trying 7.1.17 with the latest. I checked the code at the given tag and line 555 refers to what is now line 554. If by "another mod is calling that function incorrectly" you are referring to `onNeighborChange` then that could be the problem, but due to the nature of the error (a stack overflow) seeing the originating frame and related frames is simply not going to happen.

**Comment by AEnterprise** [comment]
@RomanHargrave so it's a stackoverflow? i thought it was just a non crashing error, can you give a full crashlog?

**Comment by RomanHargrave** [comment]
I can't since I can't reproduce it. The user with issues can do so reliably. I will try to point him to this thread.

**Comment by AEnterprise** [comment]
@RomanHargrave any update on this?

**Comment by RomanHargrave** [comment]
No. But I imagine that this is more of a forge issue if it's responsible for handling event triggers.

**Comment by AEnterprise** [comment]
it's indeed eighter a forge issue, some variant of bukkit/thermos/... messing with it or a mod calling that function with incorrect parameters

**Comment by AEnterprise** [comment]
closing due to lack of new information
