### ISSUE TITLE
blueprint do not show machinery

### ISSUE THREAD

**Issue by thiagomgp** [BuildCraft/BuildCraft#3387]
hello, I use galactricaft mod and the blueprint do not save aluminiun wire, oxygenium compressor and others, but save the blocks like decoration tin, please verify that.

since now thankyou

**Comment by AlexIIL** [comment]
This is most likely due to aluminium wire being a complex block (i.e. a tile entity) and so buildcraft cannot properly support it without galactricaft providing a way to save and load those blocks. However decoration tin is most likely just a normal block with no special behaviour required, which is easy to support in BuildCraft. You would have to ask galacticraft to provide support for the builder.
