### ISSUE TITLE
Random (?) chunks being loaded permanently and issuing a lot of tickets

### ISSUE THREAD

**Issue by CorentinJ** [BuildCraft/BuildCraft#3411]
![image](https://cloud.githubusercontent.com/assets/12038136/17507312/4980efb4-5e0f-11e6-859f-efa3a4d738eb.png)

Where my mouse cursor is you can see a few chunks being loaded. The area is apparently constantly loaded and approaching it causes lag. I've never built anything there, just came a few times close for exploration/mining purposes. Also I can remember seeing these kind of "spots" in much older packs (about 3 years ago). Is it just some sort of convenient hack?

Pack used: Infinitech2 v3.2.10
Java version: 1.8.0_91

**Comment by asiekierka** [comment]
The only thing that should be loading chunks is the Quarry, so, try
disabling quarry chunkloading?

2016-08-09 9:01 GMT+02:00 CorentinJ <notifications@github.com>:

**Comment by CorentinJ** [comment]
![image](https://cloud.githubusercontent.com/assets/12038136/17509944/d34a109c-5e1c-11e6-87f1-932ee8f63af0.png)

Doesn't help :/

**Comment by AEnterprise** [comment]
so there is absolutely nothing in that chunk other then natural worldgen?

there are 6 blocks loading 6 chunks and from the image it looks like an evenly spaced out pattern, not something random. can you do profiling of what exactly is using up so much ticktime causing the lag? that might shine some light on what's heapening. a log would also help as that area is using 200 tickets while it should be using a max of 6 (1 for every chunk). forge might be logging an error about the max amount of tickets being reached and what is requesting all those tickets.

whatever it is: it's not an intentional hack but i suspect an error in the code of whatever is chunkloading those chunks.

**Comment by CorentinJ** [comment]
[Here is a video](http://puu.sh/qv6mZ.mp4). I _really_ haven't built a quarry there, it's even disabled by gregtech. And I did disable the quarry chunk loading.

[Here are the logs of that session only](http://puu.sh/qv6xk.zip), I hope those are the ones you expected.

**Comment by AlexIIL** [comment]
Can I see your "forcedchunks.dat" file in your world save folder? It might give us more information (or whichever one is the dimension you are in)

**Comment by AEnterprise** [comment]
looking at the video something wonky is going on: there are 555 quarries in your world

i'm not exactly sure what the colors on the opis map are but i'm suspecting red is everything that's loaded, if that's so then it looks like those red dots you see when flying away are quarries (or something else, never used opis that much)

looking at the logs there isn't anything suspicious in there, there are a few errors but those are unrelated (somthing going wrong with a tooltip)

**Comment by CorentinJ** [comment]
The map is from chickenchunks AFAIK (/chunkloaders) and the red dots are only the chunks being currently loaded (see how a big red square moves around me)

Here is [forcedchunks.dat](http://puu.sh/qv89o.dat)

**Comment by AEnterprise** [comment]
looking at the file there are indeed alot of quarries loading chunks can you take a look at X:-410, Y:32, Z:625 ?

that's one of the quarries but it looks like it's part of an a cuboid made entirely out of quarries

**Comment by CorentinJ** [comment]
I'll have a look (takes a good 10 mins to load).  Imagine if it was a wolrdgen ID error hahaha, [that wouldn't be the first time](http://imgur.com/a/9BpaZ)

**Comment by AEnterprise** [comment]
it should not be but with your modlist i wouldn't rule it out eighter. i didn't go though it all but it's a long list so there might be a mod in there messing with the block registry or doing something wonky to the world generator. ID conflicts and the mess that came with it sould no longer exist though since mods don't assign numeric ID's to their blocks and items anymore, we only asign a name and let MC and forge take care of the rest

**Comment by CorentinJ** [comment]
Bingo! It's a big sphere made of quarries... I'll be proceeding to dig it out. I should mention I had disabled some mods which may have caused the ID problem.

So sorry for posting an apparently non BC related issue and thank you very much for your time.

**Comment by AEnterprise** [comment]
this was a BC issue, there's just another mod involved that caused all those quarries to be there and cause the issue but glad the problem is solved now
