### ISSUE TITLE
Server crashes on startup after opening an OpenComputers Computer Case

### ISSUE THREAD

**Issue by GuyInGrey** [BuildCraft/BuildCraft#3457]
I tried to upload the log the Pastebin, but there text size limit held me back. Here is a file link (Uploaded to my site):
http://gaminglem.ddns.net/log
http://gaminglem.ddns.net/log2

The first time I create a world on my Minecraft server, I can join fine. But the moment I open an OpenComputers Tier 3 Computer Case, everything goes wrong. The server immediately crashes, and from that point forward, crashes on startup. I have look for others having this error, but I cannot find anything relevant to my problem. I'm posting it here because the crash section at the bottom of the log reapetedly references BuildCraft. Anyone have a solution?

P.S. I believe it is an issue from BuildCraft trying to read the amount of power in the computer case, but I could be wrong.

**Comment by AEnterprise** [comment]
the issue seems to be something going wrong with the OC traits where it's trying to fetch a power provider but can't find the internal OC function

eighter there is something going on with an mismatched OC/BC version or an outdated OC api but nothing can be done from the BC side as it's all OC code, try reporting to them

**Comment by GuyInGrey** [comment]
OK, I'll do that! Thanks for your help.
