### ISSUE TITLE
move development to 1.11

### ISSUE THREAD

**Issue by AEnterprise** [BuildCraft/BuildCraft#3460]
ok i'm not realy helping on the dev but i think it should move to 1.11.

the reason for this is some of the big changes: itemstacks have changed, null is no longer allowed, instead there is a function to call to see if it's a valid stack or not. this means all code would need to be looked over, the null checks removed and replaced with the new system (there are other things but this would be the biggest)

as BC is still undergoing it's rewrite i think it would be best to move now while there is still work being done then after and then having to go through all the code again

**Comment by LuigiHutch** [comment]
I think it could/ should wait till forge releases a stable build as there are still breaking changes being made and developing on a stable build is better than developing on an ever breaking build

**Comment by AEnterprise** [comment]
forge is at the end of breaking changes, unless there is a real good reason there shouldn't be any more breaking changes and non are in the works realy so the chanse of a breaking change is very slim

also just a discussion for now to get ahead of it so the decision to move or not can be made by then

**Comment by AlexIIL** [comment]
I'm migrating to 1.11 in a separate branch locally, fortunately it's not that much work (a few methods changed signature, and itemstacks can be migrated with lots of null annotation checking.)

It's also quite important to migrate (or at least start) before forge has finished making breaking changes so that we can check to see if any additional changes might need to be made.

I'll probably push it to 8.0.x main after (a) I am finished, and (b) there are no PR's open requesting to be pulled.

**Comment by AlexIIL** [comment]
Oh and (c) when forge is out of beta as itemstacks seem to be a bit off atm

**Comment by AEnterprise** [comment]
yeah, they are still finishing up, the itemstack changes are huge but not binary breaking so it's hard to get it in all places

**Comment by Enter03** [comment]
I think that before the release of BC for MC 1.11, you should release version for 1.10.

**Comment by asiekierka** [comment]
People say so about every version until everyone else moves on anyway. No release > Rushed, buggy release-------- Wiadomość oryginalna --------Temat: Re: [BuildCraft/BuildCraft] move development to 1.11 (#3460)Od: Enter03 Do: BuildCraft/BuildCraft DW: Subscribed I think that before the release of BC for MC 1.11, you should release version for 1.10.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BuildCraft/BuildCraft","title":"BuildCraft/BuildCraft","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BuildCraft/BuildCraft"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Enter03 in #3460: I think that before the release of BC for MC 1.11, you should release version for 1.10."}],"action":{"name":"View Issue","url":"https://github.com/BuildCraft/BuildCraft/issues/3460#issuecomment-267350678"}}}

**Comment by AlexIIL** [comment]
@asiekierka you might want to clean up how you reply to issues via email :P

**Comment by AEnterprise** [comment]
@Enter03 we will have to see about that, if 1.11 becomes stable and mods start migrating before BC is stable enough for a release there most likely won't be a 1.10 release

**Comment by P1st0lpr0** [comment]
I'd say it would be better for the players to first do a 1.10.2 release, and then a 1.11 one. Alot of players are playing 1.10.2 (including me).

**Comment by AEnterprise** [comment]
if there is a 1.10.2 release or not will depend on how far into the cycle current BC development is, if it's close a 1.10.2 release might be possible, if not it'll be 1.11

**Comment by AlexIIL** [comment]
I can guarantee that there won't be a 1.10 release, this issue is to manage when the 8.0.x-1.11.x branch is merged into the master (8.0.x) branch

**Comment by AlexIIL** [comment]
Actually I don't think ther's much point in this issue being open: I'll merge in 8.0.x-1.11.x whenever the 1.11 port is done, and its fully up to date with the 8.0.x branch

**Comment by ViperZeroOne** [comment]
Personally, I think it would be much better to go with 1.10.2 first as there are a lot of mod pack developers (myself included) who have been patiently waiting for a release on that version.  The upgrade to 1.11 afterward shouldn't be a big problem.

**Comment by LuigiHutch** [comment]
Too late :D. Development has already moved to 1.11.2

**Comment by asiekierka** [comment]
@ViperZeroOne Minecraft 1.11 modifies a lot of ItemStack code. BuildCraft relies on a lot of ItemStack code.

Going to 1.10.2 first, especially with a rewrite and not a port, would just cause more bugs in the long run - besides, don't expect *any* release for the time being.

**Comment by Kuktar** [comment]
This saddens me. Many modpack markers will not move 1.11. There working hard on 1.10. Are there even any modpacks that are 1.11. 

Most users are making the move from 1.7.10 to 1.10.2 becuase alot of mods are supported now on 1.10.2. 

Other than alot of extra work why is any moder doing 1.11 instead of 1.10 first...

**Comment by AEnterprise** [comment]
because BC is nowhere near stable or complete enough to be usable in any modpacks, mods will have moved to 1.11 by the time BC is done

**Comment by asiekierka** [comment]
@Kuktar They said the same about 1.8 in relation to 1.7.10, about 1.7.2 in relation to 1.6.4, about 1.5.2 in relation to 1.4.7.

It's better to prepare for the inevitable, especially for a mod you probably won't see before 1.12 snapshots start coming out.

**Comment by Fungie2134** [comment]
Were can I find the old 1.10.2 branch? Since you moved to 1.11.2 I am trying to make it work...

**Comment by AEnterprise** [comment]
there has never been a 1.10.2 branch, development jumped straight from 1.8 to 1.11, you will probably have to start from the 1.11.2 branch and backport to 1.10.2

**Comment by Fungie2134** [comment]
@AEnterprise I know a 1.10.2 branch existed.
@AlexIIL Thanks, I will start from the 1.10.2 branch and backport 1.11.2 change.

**Comment by AEnterprise** [comment]
@Fungie2134 what i ment was that there is no branch specificaly for 1.10.2 as that branch is now 1.11.2

also i think it might be easier if you start from the 1.11 branch and then look at what doesn't work and backtrack the change instead of having to apply 6 months of commits

finaly if you get it to a working state that could be released please let us know so we can setup a seperate branch for it where you can point a PR at seperate from the current 8.0.x branch

**Comment by Fungie2134** [comment]
I tried it, and yes I think it will be easier to start from the 1.11.2 branch. This old branch is broken.
I will make a fork after getting a first version working. And, there no so much change between 1.10.2 and 1.11.2 API, I think.
@AEnterprise Thanks, and sorry for this misunderstanding.
