### ISSUE TITLE
[7.1.20] Pump cause crashes

### ISSUE THREAD

**Issue by StGorynych** [BuildCraft/BuildCraft#3495]
If i place a pump, it causes server crashes. Only way to fix it is remove a pump. Before it i should keep away from chank where a pump is placed.

http://pastebin.com/fxmHcKWg

**Comment by asiekierka** [comment]
What on earth are you trying to pump that a pump queue rebuild takes 90+ seconds?

Do note that we generally do not resolve Cauldron issues, as the only correct answer is to remove Cauldron - many parts of BuildCraft will intentionally switch to more Cauldron-friendly but *slower* code in order to maintain at least an illusion of correct functioning.

**Comment by asiekierka** [comment]
Nevermind, reproduced without Cauldron by someone else.

**Comment by asiekierka** [comment]
Here's a test build which, according to GregoriousT, should solve the problem:

http://asie.pl/bc7121-3495.jar

Please report back.

**Comment by asiekierka** [comment]
GregT says it fixed the problem.

**Comment by AEnterprise** [comment]
closing this as it's fixed then, 8.0.x won't have this issue with the blockstate changes
