### ISSUE TITLE
/ by zero error

### ISSUE THREAD

**Issue by Leecook337** [BuildCraft/BuildCraft#3500]
I know how I made the error, just need to know how to fix it? I reset the config files and world buildcraft data folder. But I still get that error along with crashing when I login. 

http://pastebin.com/YKpcaTGb

**Comment by afdw** [comment]
Log is not full. Can you please paste full log or say version of BC?

**Comment by AEnterprise** [comment]
https://github.com/BuildCraft/BuildCraft/blob/7.1.x/common/buildcraft/builders/TileQuarry.java#L658

you are gona have to use mcedit or something similar to remove the quarry you placed to get back in your world.
due to the config accepting 0 as value for the quarry energy options the quarry you placed down has a max capacity of 0 and that is saved to it's nbt and used to recreate the battery on loading (thus with 0 capacity again) so we should probably not allow a value of 0 or lower in the config options

**Comment by asiekierka** [comment]
The battery is *not* used to recreate on loading for the quarry in particular.
