### ISSUE TITLE
Buildcraft 7.99.x Doesn't Have kinesis Pipes

### ISSUE THREAD

**Issue by restructor** [BuildCraft/BuildCraft#3523]
Hi, I'm returning to play minecraft version 1.11.2 and i've installed builcdraft 7.99.0 and i don't know if is my installation but i don't see any kinesis pipes, can't craft robots or the pump. it's a bug or it is normal in this version?

**Comment by AlexIIL** [comment]
They haven't been ported yet.

**Comment by LuigiHutch** [comment]
Where did you download it from? Did you know it is in alpha?

**Comment by AEnterprise** [comment]
@LuigiHutch the version is on curse (marked as alpha) for testing, not many people seem to look at the BC site as well so i threw it up the curse site so people could test (and so i wouldn't get daily complaints still haven't found the spammer or how he got my email)

**Comment by LuigiHutch** [comment]
Yes I know, I wanted to know if they knew it was in alpha as it it very easy to download it without knowing its in alpha on the curse client. If they didn't know it was in alpha, I would be surprised if we get many more reports like these from curse users

**Comment by AEnterprise** [comment]
it's marked as alpha so only visible on site, not in the client

**Comment by LuigiHutch** [comment]
Well it is actually available on the client, just create a new profile with the preferred release type as release and it will still show the alpha release of BC.

**Comment by LuigiHutch** [comment]
This is why BC had a no alphas on curse policy

**Comment by AEnterprise** [comment]
@LuigiHutch thanks for letting me know then as that is a curse bug then, alpha's should not be visible in the client at all, i'll contact their support for it
![image](https://cloud.githubusercontent.com/assets/5206666/25063374/d169f9a6-21e2-11e7-8d9e-cc7c3c4ee67b.png)

**Comment by LuigiHutch** [comment]
Well I did tell Zeldo on irc, he just seemed to ignore it/miss it.

**Comment by AEnterprise** [comment]
i'll get on it and get them to eighter fix it or i'll archive the file, can you get me a screenshot?

**Comment by LuigiHutch** [comment]
![cure profile options](https://cloud.githubusercontent.com/assets/9326429/25063447/8081149e-21dc-11e7-985b-4372616cdeab.png)

![cure bc download](https://cloud.githubusercontent.com/assets/9326429/25063448/86a816b0-21dc-11e7-8ddc-d578d2f02ea5.png)

![cure alpha bc download](https://cloud.githubusercontent.com/assets/9326429/25063450/89aa9d1a-21dc-11e7-9005-0ab670d6d007.png)

**Comment by AEnterprise** [comment]
ok i kinda talked to support, they have no clue when someone might look at the issue (i might not even get a reply notifying me when it's fixed) so what are we gona do with the file?

as stated by @AlexIIL and @asiekierka it's against our alpha policy since it does sync to the client and is thus easely added to modpacks in it's unfinished state

on the other hand the file is already on there and people are using it

i could eighter leave things as is or archive the file, thoughts?

**Comment by AEnterprise** [comment]
@AlexIIL @asiekierka thoughts on if the file should stay or be removed?

**Comment by SambalMinion** [comment]
As a user of the client, my needs would be met completely if the mod overview page for BC contained a two-line comment indicating that 7.99.0 is an Alpha and what I can expect to work/not work. I appreciate the effort you guys are putting into BC. thanks!

**Comment by asiekierka** [comment]
@SambalMinion Isn't the fact 7.99.0 is marked as "Alpha" on CurseForge enough?

(I'd also like to point out that, officially, CurseForge is considered a mirror of http://mod-buildcraft.com/pages/download.html )

**Comment by SambalMinion** [comment]
@asiekierka
The curse client does a shit job of informing users of BC's 1.11.2 alpha status. Their fault, not yours. A message that shows up on the page shown in the client is merely a bandaid. But maybe a worthwhile one, at least while alphas show up on the client.

I think that any other modality offer plenty indication that 7.99.0 is alpha:
- 7.99.0 is not immediately visible on curse.com.
- both the curse.com and the curseforge download buttons default to 7.1.21.
- If you're looking for 7.99.0 you'll find it, but not without also bumping into the alpha designation.

On the client, the only place where the alpha designation is visible, is on the 'versions' page - and a user has no business there unless they happen to be looking for a specific version for compatibility reasons.

**Comment by asiekierka** [comment]
@SambalMinion 7.99.1 seems to add a warning on world join, that may be a bit helpful as well.

**Comment by AEnterprise** [comment]
@asiekierka i'll be adding a warning in the changelog and at the top of the curseforge project description when uploading 7.99.1, allong with a note that there will be no backport and asking about it is useless

**Comment by asiekierka** [comment]
@AEnterprise Don't be so harsh; just state that a 1.10.2 backport is not currently planned. No need to take it out on the users.

**Comment by AEnterprise** [comment]
@asiekierka sorry i didn't mean to be harsh, just getting fed up with the PM's and emails (already blocking some emails and had to report someone already)

**Comment by Rambo99** [comment]
Instead of just closing posts with errors, is not it easier to fix YOUR mistake? Is it so difficult to add **8 standard recipes that existed in previous versions**?! Or maybe **YOU** just **LAZE**?!

**Comment by asiekierka** [comment]
@Rambo99 

Yes. It's actually pretty difficult.

As a historical sidenote, the BuildCraft Kinesis Pipes (and yes, we're going to insist on calling them Kinesis Pipes. BuildCraft does not consider the energy it uses to be electric in nature, rather, it's more kinetic - this was more visible when MJ was around, however) had many bugs in early versions of BuildCraft and took many attempts by many developers to get just right in terms of behaviour. You seem to take them for granted - please don't. Try playing an older version of BuildCraft - like, BuildCraft 2.2 "old".

In the current 1.11.2 release, they literally don't exist. The pipe code is being fully rewritten, and there is no way to restore them without putting in significant effort to adapt the old algorithms to the new code. In other words, kinesis pipes literally don't exist in any way, shape or form right now on 1.11.2, and recipes are by far the easiest part - though recipes won't help you much when the pipes don't do anything. That effort is going to be put in by the current development team at some point in time, but they are already overworked with rewrite and bugfixing efforts in other areas of BuildCraft.

Also, **WE** can be as **LAZE** as we want. You're not paying us for this. You haven't signed a contract with us. You haven't received any warranty or promises as to when the features will be delivered. The developers are doing this because they love to do it, because it's their hobby - and features are going to be released when they are ready.

If you cannot accept that your hostile demands are not going to be taken into account by the development team, I welcome you to use a different mod. We don't mind.

By the way, you forgot to add the **bold** formatting to the other post when you were reposting it [here](https://github.com/BuildCraft/BuildCraft/issues/3692). You might want to try again.

**Comment by AlexIIL** [comment]
Kinesis pipes have been (mostly) reimplemented in 7.99.5, and recipes in 7.99.6.
