### ISSUE TITLE
Quarry lines are glitched into the world [Pretty Urgent]

### ISSUE THREAD

**Issue by mike40376** [BuildCraft/BuildCraft#3524]
I moved a world from one modpack to another and I kind of broke it. I really do not want to restart because of the amount of work I put into making a living area. Is there any way to go into server files and delete these lines because its lagging my friends games out. 
![2017-04-15_17 36 20](https://cloud.githubusercontent.com/assets/25348892/25066926/3e933c80-2202-11e7-9928-b588a7d12ec4.png)

**Comment by LuigiHutch** [comment]
BC version? Forge version? MC version?

**Comment by mike40376** [comment]
MC - 1.7.10
Forge - 10.13.4.1614
Buildcraft - 7.1.16
I switched the map over from Tekkit to FTB Inventions if that helps

**Comment by LuigiHutch** [comment]
As a guess, it seems like some ID corruption leading to some quarry's to spawn nearby. 

Have a look and see if there are any quarries nearby, if so try and remove them by hand or with mcedit.

**Comment by mike40376** [comment]
I removed all the quarries before i ported the map over

**Comment by LuigiHutch** [comment]
Have a look again in the ported over map as it may have made some due to an block ID shift

**Comment by mike40376** [comment]
There was a block ID shift. I ended up exporting the structure into a map generated with the newer version but when I did that it exported some of the things that make the lines appear. Ore in the walls turned into quarries.

**Comment by AEnterprise** [comment]
sadly there is nothing we can do about this, mods where removed causing id's to be freed up and new mods added that are taking up those id's

the only thing you could try (if you have a backup of the world from before loading it with the new modpack) is comparing the modpacks, make a custom instance based on the original modpack but remove all the mods that are not in the new pack, this will cause the block id's to already free up but since you didn't add the new mods those id's are free and not used by other mods (yet)

load up the world and fly around making sure all the chunks that already have been generated get loaded atleast once (or at the least the area's that you care about) when the chunks load the removed blocks should be set to air, meaning they will be saved as such and not an non-exising id that another mod might use later

now you can load the world with the new modpack, blocks will get new id's but forge should be able to find all the old ones, remap internaly and load up without blocks changing

one warning: it might or might not work, there are some mods (especialy in 1.7.10) that hack the forge registries and force id's their own way, if that's the case id shifts can't be fixed
