### ISSUE TITLE
Quarry perfomace issue

### ISSUE THREAD

**Issue by XakepSDK** [BuildCraft/BuildCraft#3571]
Is it ok?
https://timings.aikar.co/?id=1427a6ae9dbe437491b12ef8a5401544

**Comment by LuigiHutch** [comment]
Forger version?
BC version? 7.0.0-BETA-0 is not an official version

Update to 7.99.3 and see if that helps. Also do this as it will be easier to determine whats wrong: https://www.reddit.com/r/feedthebeast/comments/5mxn51/vanilla_has_an_built_in_profiler_that_not_a_lot/

**Comment by AEnterprise** [comment]
@LuigiHutch 7.0.0-BETA-0  is the timings version he's using afaik

but yeah we need BC and forge versions

from a quick glance though it looks like this is a sponge (or alternative) server with a anti-grief plugin, it also looks like there are 428 quarries ticking and alot of entities joining the world (aka quarries spitting out items in the world because they have no valid output)

we would also need a more detailed profiling to figure out what's exactly causing lag, it only shows the quarry self time is massive but that's alot of code doing alot of different things

**Comment by XakepSDK** [comment]
Forge 13.20.0.2296
7.0.0-BETA-0 - latest spongeforge, manually builded.
BuildCraft build: b9fc41d903a10fecd85452617bf5ca311e077c39
Quarry:
https://puu.sh/vOBby/4188b22bed.png
Frames size: 27x5x33

**Comment by AEnterprise** [comment]
@XakepSDK does this still heapen on a pure forge server without spongeforge? if not it's spongeforge issue (some of their optimizations or protections tend to backfire on forge mods)

**Comment by XakepSDK** [comment]
Okay, i can't reproduce this.
Latest report:
https://timings.aikar.co/?id=d8b54f4555864c5c8cebcbb4ea556293

But i found another issue with quarry.
https://www.youtube.com/watch?v=juhzHOVcY-g&feature=youtu.be

**Comment by AEnterprise** [comment]
if you can't reproduce you'll have to talk to the spongeforge team for a fix

as for the 2nd issue: your reports indicate you are having tps issues with all that is loaded on your server so the delay is most likely due to that
