### ISSUE TITLE
Oil is invisible with shaders mod

### ISSUE THREAD

**Issue by kleiner-sentry** [BuildCraft/BuildCraft#3642]
when i pour a bucket of oil in minecraft with shaders mod it looks invisable, but still casts a shadow.
Please fix.

**Comment by afdw** [comment]
Minecraft and BuildCraft version?

**Comment by kleiner-sentry** [comment]
1.11.2

**Comment by AEnterprise** [comment]
@kleiner-sentry i'm gona assume here that it is 7.99.4? latest doesn't tell all that much as sometimes say people latest but it has been weeks since they checked for an update

also what mod are you using for the shaders? does it only heapen with a specific shader or all of them?
since this works just fine without any shaders mods this is most likely an issue with the mod itself or it has a problem with our textures, did you check with that mod for know issues or report it to them as well?

**Comment by AEnterprise** [comment]
closing for a lack of information about other mods/shaders involved. shaders mess with the rendering and if you are using optifine (like 99% of those using shader packs) we cannot fix this without info from the optifine dev about what exactly is going wrong here

if you can provide the needed info please comment on this issue and we can re-open to take a look
