### ISSUE TITLE
[1.11.2]Issues with Builders module

### ISSUE THREAD

**Issue by Royal-Jelly** [BuildCraft/BuildCraft#3647]
architect table output an item fine but the item wouldn't save to the library so i moved it from the snapshots-server folder to snapshots-client folder, went to make the blueprint in another world and the game froze without crashing [here's my log](https://paste.ee/p/v8d5C)

**Comment by AEnterprise** [comment]
looks like a to large packet was being send so we need to split that message (can you dive into this @afdw ?)

also semi related there is alot of spam in your log from betterfps spitting errors from the creative menu, you might want to report to them with that log. Some info for them: the issue seems to be them trying to clear a NonnullList that has no default value to fill the list

**Comment by Royal-Jelly** [comment]
Made a fresh instance with only buildcraft and here is [what my log spits out](https://paste.ee/p/yhXm6)

Im not exactly sure but without the mods installed it does through that in the log and boots me out of my world, with mods it just freezes which is weird ...

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
