### ISSUE TITLE
buildcraft quarry break air

### ISSUE THREAD

**Issue by MrXromik** [BuildCraft/BuildCraft#3661]
![2017-06-09_19_18_01](https://user-images.githubusercontent.com/12598688/26985482-47da4ef8-4d4c-11e7-94ba-f78f44d2fe48.png)
Buildcraft version 7.1.22

**Comment by AEnterprise** [comment]
what other mods do you have installed? is this singleplayer or on a server (and if it is on a server is it a regular forge server or running bukkit/sponge/...)?

is it actually trying to break blocks (halting at every block and/or showing break animations) or is it just moving over it very quickly?

**Comment by MrXromik** [comment]
it server on thermos.
trying to break air.

**Comment by afdw** [comment]
Is that vanilla air? Or something air-like from other mods?

**Comment by MrXromik** [comment]
Vanilla air

**Comment by MrXromik** [comment]
Ohhh, quarry dont break air.  is it just moving over it very quickly. Falls on 6 blocks of air and then back to the top.

**Comment by MrXromik** [comment]
I found a problem, if 2 quarry in one chunk and the player departs from them for 10-15 minutes, then one of the quarries stops working.

**Comment by AEnterprise** [comment]
@MrXromik can you download the world and open it up with somethink like MCEdit and check those blocks to make sure they are actually vanilla air and there isn't any TE or anything else that should not be there at that position?

if it is just vanilla air then there must be another mod (or thermos) messing with it because the only reason the quarry should be returning to already dug up positions when it is already running would be if it detected that there is a block at that position

**Comment by AEnterprise** [comment]
closing as this is thermos/bukkit/... or another block messing with eighter the air block itself or a fake air block and messing up the quarry logic as a result
