### ISSUE TITLE
[1.11.2](7.99.4) Can't craft few items. 

### ISSUE THREAD

**Issue by Bolo02** [BuildCraft/BuildCraft#3673]
Hi, I can't craft few items. Only Quarry and Mining Well crafts ok but I don't check all items from mod. My Forge is 1.11.2-13.20.0.2296.
Things I already done:

- Reinstall Minecraft (few times)
- Reinstall Forge (few times)
- Try all 7.99.X Buildcraft versions
- Deleting Buildcraft Config file 

Here screenshots:

![2017-06-15_14 23 11](https://user-images.githubusercontent.com/29456538/27182118-86d31bb6-51da-11e7-8e49-f2411700e1a7.png)
![2017-06-15_14 23 32](https://user-images.githubusercontent.com/29456538/27182134-8e1f1ec4-51da-11e7-821e-69a61f754778.png)
![2017-06-15_14 27 26](https://user-images.githubusercontent.com/29456538/27182139-914051d6-51da-11e7-9f5d-16d0c48e15c3.png)
![2017-06-15_14 27 56](https://user-images.githubusercontent.com/29456538/27182144-93518e04-51da-11e7-9e87-2b2590007408.png)
![2017-06-15_14 52 00](https://user-images.githubusercontent.com/29456538/27182150-95485490-51da-11e7-81ec-4f9865ee3ade.png)

**Comment by AEnterprise** [comment]
not everything indeed has a crafting recipe at this point and some got changed (you can look them up in JEI)

BC is also still in early alpha so not completely ready for survival usage, if you see things in JEI that are not craftable it is most likely because it is not ready for that yet. I will take a look at what we have though to see if any others are ready for survival testing probalby later

**Comment by Bolo02** [comment]
Thanks for fast anserw. I have 2 more questions.
1)What is JEI?
2)So only I can do is waiting for fixed versions?

**Comment by AlexIIL** [comment]
To view current available recipes you can either craft a guide book (1 wooden gear + 3 paper) or install JEI (a separate mod, however it doesn't show recipes made in the assembly table yet)
