### ISSUE TITLE
[1.11.2] (7.99.4) Crash with CofH Mod Collection

### ISSUE THREAD

**Issue by Terpo** [BuildCraft/BuildCraft#3675]
I tried the latest official release and a selfmade build from a few minutes ago with forge 2315.

Crash happens on the end of the loading phases on client and server.
Client does not reach the main menu.

https://gist.github.com/Terpo/1bd4db593d9b6bd28f9822c4dd944ab2

https://twitter.com/KingLemmingCoFH/status/876209775134027776

**Comment by AEnterprise** [comment]
it looks like COFH is crashing because we are trying to detect all fluid containers for lists as examples, probably need to catch errors like this (though they should probably also make sure not to crash when NBT is missing, that tends to heapen in MC on occasion between mods)

probably also best to look into why we are doing it exactly and if it even works like intended, first glance says it's for examples of fluid containers but if we are only checking that list to see if an item is a fluid container it won't work

**Comment by AlexIIL** [comment]
Should be fixed if they merge https://github.com/CoFH/ThermalExpansion/pull/5 or similar

**Comment by KingLemming** [comment]
I've handled it on my end, but in general I'm not sure what you guys are doing is a good practice. I was able to eschew NBT checking there because the only ItemStacks that should have ever been in existence were from the tank block itself, and had the NBT properly assigned.

**Comment by AEnterprise** [comment]
we do need to look at if that code is needed or not but it is ment to look for fluid storing items to show when filtering similar items

**Comment by AlexIIL** [comment]
Because it's on the client side we can probably replace that with a creative inventory sub items lookup instead. (Which would also handle differing levels of items nicely). However I'm not sure about the ic2 crash, as it looked like it was related to recipe creation. Obviously I have no idea about what they are trying to do though

**Comment by KingLemming** [comment]
If this is client-side only, then use getSubItems to get allowable ItemStacks. That's what JEI does, and my JEI integration definitely doesn't crash or explode.

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
