### ISSUE TITLE
Incompatibility with Random Things

### ISSUE THREAD

**Issue by 23Link89** [BuildCraft/BuildCraft#3704]
Using Forge 13.20.1.2393
Using BuildCraft 7.99.4
Using Random Things 1.11.2-4.0
Using MC 1.11.2
Crash with Random things installed: https://pastebin.com/1GmXvNj6

**Comment by AlexIIL** [comment]
This is the same crash as #3689, which is reported in ToughAsNails's repo in https://github.com/Glitchfiend/ToughAsNails/issues/274 -- can you try removing one of "Tough As Nails", "Extra Utilities", and "Random Things" and launching again?

Either way this isn't caused by buildcraft, but buildcraft happens to call a method that has been modified by a coremod incorrectly.
