### ISSUE TITLE
iron pipe doesn't work sometimes

### ISSUE THREAD

**Issue by traso56** [BuildCraft/BuildCraft#3736]
Hello,
I tried using the clay pipes to fill some containers but it only works right next to the block which is fine so i used gates and iron pipes to get the same result and it works pretty good in the first 3 iron pipes but the fourth just sends items back even if visually it should send them to the south so i changed the gate to send signal when empty instead of some space and it worked but the same problem repeats in the 5th pipe i didn't test if it worked if i invert the signal here too but is there a reason this happens? thanks

http://i.imgur.com/3yRt7l4.png

**Comment by traso56** [comment]
i solved it by inverting every pipe and breaking an replacing the stone pipes so that may help if you have this issue

**Comment by AEnterprise** [comment]
i could not reproduce this issue at all, it sounds like you had it misconfigured, if you have a line of iron pipes it might be a bit harder to see what each pipe is pointing towards

also you don't need these iron pipes in this scenario, you can use the clay pipes and have the pipeline directily on top of the machines instead of one block higher
