### ISSUE TITLE
Quarry needs to be placed by landmark corners for landmark dimensions to apply

### ISSUE THREAD

**Issue by jarmund** [BuildCraft/BuildCraft#3744]
Placing a quarry next to the landmark lasers is no longer enough. It has to be right next to a landmark.

**Comment by SandGrainOne** [comment]
Hasn't it always been that way?

**Comment by LuigiHutch** [comment]
Nope, it was changed someway during the 1.7.10 era so that this would work but as shown in the 1.11.2 screenshot, it doesn't work anymore: 
![2017-07-19_23 02 57](https://user-images.githubusercontent.com/9326429/28391600-8fe272f8-6cd6-11e7-9857-85b594b528f5.png)

This feature hasn't been reimplimented in the 1.11.2+ versions yet and I believe this applies to all blocks which use the landmark systems

**Comment by SandGrainOne** [comment]
Hmm, I did play during 1.7.10, but when I think about it I probably never actually used the Quarry for anything other than a block breaker over a cobble generator.

**Comment by ron-popov** [comment]
Is it fixed ? because it works for me.

**Comment by AlexIIL** [comment]
I might have fixed this in 7.99.8 but forgot to tag this issue as fixed.
