### ISSUE TITLE
Oil spawn in mid-air on superflat

### ISSUE THREAD

**Issue by n00b7** [BuildCraft/BuildCraft#3837]
**Buildcraft** version: 7.99.7
**Forge** version: 1.11.2-13.20.1.2516

Additional information:
![2017-10-29_08 11 57](https://user-images.githubusercontent.com/11874683/32145172-510b3722-bc81-11e7-867a-90e00f7766f5.png)

**Comment by AEnterprise** [comment]
did this get applied to the 8.0.x branch as well?

**Comment by border999** [comment]
I can add to this in saying this issue is still in the 1.12.2 release. Found one exactly like this in the twilight forest.

**Comment by AEnterprise** [comment]
the twilight forest isn't a superflat so a bit of a seperate issue, you can prevent oil spawning in there by adding the dimension to the blacklist in the config

**Comment by border999** [comment]
I was just noting it because the twilight forest has a ground level at around 32 blocks up. It seems somewhat relevant that this issue is seemingly universal to any dimension that doesn't have a ground level at block 64.

**Comment by AEnterprise** [comment]
that's a seperate thing and is to avoid runaway terraingen, the determining of a ground lvl needs to be re-added but that's not easy while still trying to avoid runaway terraingen

**Comment by AlexIIL** [comment]
I suppose there are *technically* 2 different issues here: that oil spawns in superflat biomes (at all), and that the oil tendrils are hardcoded to generate at y=64, even in the overworld. The first one can probably be fixed by cancelling generation if the world type is superflat, the second might be fixable by moving where Y-level of the tendril is decided from the generation code to the normal generation code.

**Comment by AlexIIL** [comment]
Fixed by @scagood in #4271, and will be a part of 7.99.19 at some point in the future.
