### ISSUE TITLE
Planter hangs when doesn't find a path to plantable block

### ISSUE THREAD

**Issue by BoomBap420** [BuildCraft/BuildCraft#3856]
**Buildcraft** version: 7.1.22
**Forge** version: 10.13.4.1614-1.7.10
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Both

Additional information:
When a planter detects a valid spot to plant, but it doesn't find a path to it(when the spot is underground), it just hangs. This can be of huge annoyance, because the only workaround I found is to dig out every single dirt block under the farm all the way down to bedrock.
 
This could be improved by either:
 1. Making it possible to set y coordinates for work area,
 2. Making the planter find a new spot instead of hanging when it doesn't find a path(this still wouldn't fix the issue of it not going back to station). 
3. Make only spots with access valid spots.

There are probably more solutions, these are just the ones I came up with. 
Also made a video in case my description is unclear:
 https://youtu.be/ZVO_eEQqmx8
 In the video I first show how everything works correctly and then display the bad behaviour. Feel free to mute if you want :P

EDIT: Probably relates to #3518

**Comment by AEnterprise** [comment]
yeah pretty much e duplicate to #3518 

if the farming area isn't to large you can use mark the area that the robot is alowed to work in with land marks (like you would for the architect table for example) and click the marker to get a working zone instead of creating one with the zone planner, then the robot will stay in the 3d zone you designated for working and not try to go to plantable underground holes
