### ISSUE TITLE
Invalid Block Property Specified

### ISSUE THREAD

**Issue by Dockter** [BuildCraft/BuildCraft#3907]
Many MANY errors on the server startup.

Error:  https://gist.github.com/Dockter/4b98cc757e6192d127eeb4b96e67496c

Version:  Buildcraft-7.99.13-pre9.jar

Error doesn't exist on 7.99.13.pre0.jar

Let me know if you need anything further.

**Comment by AlexIIL** [comment]
Related to #3877 - but this time it looks like ic2 does something odd.

**Comment by AlexIIL** [comment]
I'll look into reporting this one later.

**Comment by Dockter** [comment]
Tested Pre10 and issue still exists.

**Comment by AlexIIL** [comment]
...right, I forgot about ic2 :/

**Comment by Dockter** [comment]
Adding "ic2" here: https://github.com/BuildCraft/BuildCraft/commit/4784c078f409fa4b2167310072a8323cc63baca8#diff-64792d4bcc482a5177376aa303115347R85 made my errors go away as expected.

**Comment by AlexIIL** [comment]
Its meant to be a reminder list, rather than an "add every mod here that doesn't do something quite right". Obviously it disables façades from that mod in question (not ideal). I'll report to the ic2 team shortly (probably tomorrow), when I've had a little look into what they do, and what they could do to fix it.

**Comment by afdw** [comment]
No errors with latest BC and IC2: https://gist.github.com/anonymous/4c68e7ec013156d5adb912f65d9cb3e0
