### ISSUE TITLE
Found new bugs In Buildcraft 7.99.12 Forge 1.12.2

### ISSUE THREAD

**Issue by Hakimie2833** [BuildCraft/BuildCraft#3932]
**Buildcraft** version: 7.99.12
**Forge** version: 1.12.2
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: 

Additional information:
When I play minecraft with Forge 1.12.2 with mods buildcraft 7.99.12, I found many bugs. I cannot play until this bugs is fix.

**Comment by AEnterprise** [comment]
i'm sorry but we do not have crystal balls, we cannot know what exactly doesn't work if you do not tell us.

please give more details about what doesn't work for us to be able to fix it (also did you check the already open issues? since the release of 7.99.12 many bugs where fixed but not released yet

**Comment by AEnterprise** [comment]
Closing for a lack of information, if you provide the requested information we can re-open and take another look at this.
