### ISSUE TITLE
Wooden Extraction Pipes Can't be powered by Mekanism Universal Cables.

### ISSUE THREAD

**Issue by MarshTheBacca** [BuildCraft/BuildCraft#3947]
Title really summarises it. The Mekanism cable doesn't show a graphical connection to the extraction pipes either. I remember in 1.6.4 that you used to be able to use Mekanism cables to power them. I really don't want to have to use engines for this -_-. I'm using a custom modpack which should be noted. The mods an be seen when downloading my modpack on technic launcher: "MarshTheModpack".

Version : 7.99.12 for Minecraft 1.12.2

**Comment by AlexIIL** [comment]
Several things don't allow you to do this:

 1. Usually to power wooden extraction pipes you would need a "power adaptor" in order to connect normal power pipes to a wooden extraction pipe. They aren't ported quite yet unfortunately.
 2. wooden power pipes require MJ, rather than the RF that Mekanism cables produce.

However fortunately there are "Pipe Pulsars", which are pluggables that can be placed directly on the wooden pipe, and act like a wooden engine and gate rolled into one. You can make them by combining a redstone engine with 2 iron ingots in an assembly table.
