### ISSUE TITLE
"Filler" machine issue

### ISSUE THREAD

**Issue by maglucen** [BuildCraft/BuildCraft#3969]
**BuildCraft** version: buildcraft-7.99.12.jar
**Forge** version: 14.23.0.2552

Additional information: 

* Filler machine won't be able to be crafted and if gotten using creative mode, when placed it won't display any texture.
* If you have created an area using landmarks, the redlines will dissapear not marking where the area was supposed to be
* Will work so slow, even with 5 creative engines at once (block will start flying to their positions really slowy (as if the computer was runing at 1-2 fps))

![2018-01-09_12 52 22](https://user-images.githubusercontent.com/27809367/34719970-39a69640-f53d-11e7-841e-1c90f88cd9d2.png)

As u can see between pictures, filler wont change the red lines to blue lines as they used to be to show us the preview are selected

![2018-01-09_12 54 09](https://user-images.githubusercontent.com/27809367/34719971-3a2f6ede-f53d-11e7-9bdc-0bc9d90cd5ec.png)

The blocks took 30-60 secs to get into that place after I switched on the system and another 30-60 secs to be placed on their places

**Comment by LuigiHutch** [comment]
0. Please update to the latest BC version
1. Some recipes in 7.99.x may seem missing and do not show in JEI, that is either because they are assembley table recipes or they are blocks which aren't ready to be used in survival. #3941
2. Basically https://github.com/BuildCraft/BuildCraft/issues/3952
3. This is why it doesn't have a recipe yet

**Comment by AEnterprise** [comment]
closing as these are all known issues with already open reports
