### ISSUE TITLE
Power

### ISSUE THREAD

**Issue by Trixz2018** [BuildCraft/BuildCraft#3974]
so seeing that you guys have dropped Redstone Flux and as I assume you know nearly all mods have dropped support for mj, i was wondering if you guys plan on going to forge energy or supporting in some way? because at the moment there is no way to really power anything?

**Comment by AEnterprise** [comment]
BuildCraft is designed to provide a challenge to players, of which power generation is no exception. RF mods generally remove said challenge, so we brought back MJ in order to encourage players to generate power in more interesting ways.

that being said MJ -> FE conversion in BuildCraft is something that is being considered, FE -> MJ isn't

for more questions about things like this feel free to join our discord to ask them there: https://discord.gg/v4geqgA

**Comment by Trixz2018** [comment]
ok thanks AEnterprise for everything
