### ISSUE TITLE
Incomplete Gate crafting recipes

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3980]
BuildCraft version: 7.99.15-pre4
Forge version: 1.12.2-14.23.1.2590
Link to crash report or log: N/A
Singleplayer or multiplayer: Both

- [ ] Gold gate has no recipe

- [ ] Diamond gate expansion not available on all gates (due to the diamond shard removal)

- [ ] Unable to apply gate expansions to any gate apart from the iron gate

**Comment by AlexIIL** [comment]
- Gold gate is made in the assembly table with a golden chipset.

 - Diamond gate expansion is the diamond chipset applied to any gate (other than the basic gate)

 - Use either a single lapis, quartz chipset, or diamond chipset on any gate in the assembly table.

**Comment by LuigiHutch** [comment]
Also due to the fact that the recipes are very inconsisant with the rest...

**Comment by AlexIIL** [comment]
The gold gate yes, that's the only one that is crafted with a single golden chipset.

The rest of the expansions have 2 different recipes: (if the gate is cheap) 4 of the material surrounding the gate, and always one chipset (or for lapis, just lapis) of the material plus the gate.

**Comment by LuigiHutch** [comment]
Thats the problem, there are 3 different ways on applying an expansion and it all depends on which gate and expansion you have/want:
3 of material crafting recipe (Cheap gates only)
1 of material in assembly table (lapis expansion and expensive gates only)
1 chipset in assembly table (expensive expansions and expensive gates only)

There is no uniformity and may seem confusing to players

**Comment by AlexIIL** [comment]
Sorry, I worded my response poorly. These are the actual routes:

 - 3 of material crafting recipe (Cheap gates and expansions only - only the iron gate with only lapis or quartz.)
 - 1 of material in assembly table *(this only applies to lapis, and you can apply lapis to any gate in the assembly table, **except for the basic gate, which cannot take any expansions**)*
- 1 of chipset in assembly table *(this doesn't apply to lapis, so either quartz or diamond chipsets. Altough you can apply it to any gate, again, except for the basic gate)*

The first route is provided so that simple gates and conditionals can be crafted early on, before an assembly table has been created. (and yes, there is sooooo much more thought that could go into this).
Adding a lapis chipset would merge the second two routes.
