### ISSUE TITLE
Natural Oil Map Color Is Green

### ISSUE THREAD

**Issue by kenijey** [BuildCraft/BuildCraft#3988]
latest BC MC 1.12.2 Forge 2600

**Comment by kenijey** [comment]
and it spawns on house in villages
![fafds](https://user-images.githubusercontent.com/24831406/35192330-fd00638e-fea0-11e7-8186-38487a5d2704.PNG)

**Comment by AEnterprise** [comment]
what mapmod is that? it works fine with journeymap and such so this is probably an issue with that mapmod

also please don't say latest but provide version numbers

**Comment by kenijey** [comment]
[fml-client-latest.log](https://github.com/BuildCraft/BuildCraft/files/1649621/fml-client-latest.log)
logs if needed
BC 7.99.14
using Xaero's minimap

**Comment by AEnterprise** [comment]
did you report this there as well? if not please do as this works fine with other maps so i suspect it's a problem in that mod (and if not he'll probably be able to tell what the problem is)

the oil and village house overlapping is a sperate issue (probably the same as the trees and oil reported a few days ago but they guy not opening a ticket for it as requested)

**Comment by kenijey** [comment]
uhm, problem is i couldnt their git and mod on curse doesnt have issues tab so.. but ok. thanks for quick replies
