### ISSUE TITLE
Fuel Bucket Bug/Refinery Bug

### ISSUE THREAD

**Issue by VanHanAtGaming** [BuildCraft/BuildCraft#4000]
BuildCraft version: 7.99.14
Forge version: 1.12.2-forgr 1.12.2-14.23.1.2555 
Link to crash report or log: No crash 
Singleplayer or multiplayer: multiplayer
Additional information: Fuel bucket is upside down. Refinery won't extract its fuel.
![2018-01-26_10 47 04](https://user-images.githubusercontent.com/35824965/35423006-8d8f59a8-0286-11e8-8a8a-a41b29d3e29d.png)
![2018-01-26_10 46 21](https://user-images.githubusercontent.com/35824965/35423116-242ececa-0287-11e8-9487-b66bc4f9aa98.png)

**Comment by AlexIIL** [comment]
In 7.99.x the oil refining system has changed. The fuel bucket is actually gaseous fuel (a gas) and is one of the final products of the refining tree. The refinery is now the distiller, and has two outputs (one at the top, and one at the bottom). Just FYI, you probably want to use redstone engines rather than combustion engines for extracting from wooden pipes (as they are *much* cheaper, and you won't loose excess power for burning fuel).

Sorry for not responding earlier.

**Comment by VanHanAtGaming** [comment]
It's ok. Thank you for the response, I really like you mod. Keep up the good work.

**Comment by AEnterprise** [comment]
closing as awnsered, if you have any more questions feel free to stop by the discord for them
