### ISSUE TITLE
Pump not pumping Oil on River

### ISSUE THREAD

**Issue by CanoLathra** [BuildCraft/BuildCraft#4015]
I tried to put a Pump at the top of an Oil Well that had sprouted in the middle of a river. The nearby Oil Wells that were not on a river worked fine, but with this one the Pump refuses to pump any fluids. 
I first tried the same setup I had used elsewhere (Combustion engine to Wooden Kinesis to Golden Kinesis to Pump, Pump to Golden Fluid to Tank). I then tried using Creative engines to test, as well as trying every combination of insertion and extraction fluid pipes I could. In all tests, the result is the same:
The Pump extends down into the Oil, and the engines run up to full speed, but no fluid goes into the fluid pipes or the tanks.

Screenshot:
![2018-02-03_15 27 35](https://user-images.githubusercontent.com/16842723/35771728-fd514a6e-08f6-11e8-8653-3af26f125bac.png)

BuildCraft version: 7.99.14
Forge version: 14.23.2.2611
Link to crash report or log: 
Singleplayer or multiplayer: Singleplayer
Additional information:

**Comment by CanoLathra** [comment]
UPDATE: Fixed itself after unloading and reloading the world. Leaving the area and manually reloading the chunk did not work; I had to quit to title and reload the world.
After reloading, it pumped oil until the water spilled over the oil, then it pumped water (as expected).

**Comment by AEnterprise** [comment]
i see your problem: you have a loop in your kinesis pipes, with the way the things work this causing an overflow of the system after a while

the pump (and things further on the line) are requesting power, pipes request as much power as the sum of their neigbours, since you have a loop this is causing requests to 'loop' around, constantly increasing until eventually you get an overflow and things corrupt themselfs

**Comment by AEnterprise** [comment]
gona close this this is just a powerloop overloading the requests, for now avoid powerloops
should get fixed when MJ mechanics get implemented
