### ISSUE TITLE
Why buildcraft dont work with galacticraft

### ISSUE THREAD

**Issue by xpatryk89** [BuildCraft/BuildCraft#4081]
BuildCraft version: 7.9.9.7
Forge version: 
Link to crash report or log: 
Singleplayer or multiplayer: 
Steps to reproduce: 
Additional information: 
in older versions eg 1.6.4 buildcraft pipes worked with galacticraft, galacticraft fuel with buildcraft, buildcraft fuel with galacticraft it was very good, because i was able to e.g. use battery from galacticraft to buildcraft projects. can you give me back compatibility with galacticraft? pipes, fuel, all things.

**Comment by AEnterprise** [comment]
7.9.9.7 does not exist, if you mean 7.99.7 please update to the latest for you MC version 7.99.8.1 if you are on 1.11.2)

kinesis pipes no longer work because BC is using MJ instead of RF now and no mod is suposed to support is while we are still in alpha and the api might break

fuel refining changed completely, as a result GC might no longer recognize them, they also had a bug a while back that caused BC integration for fuels on their end not to load so make sure you update GC as well
