### ISSUE TITLE
Filler and Quary Energy and Speed

### ISSUE THREAD

**Issue by spitfire1081** [BuildCraft/BuildCraft#4085]
--> The machines FILLER and QUARY are both working very, VERY slow using the Creative Engine. The Combustion energy is what powers them the best way, but still too slow in comparison to the previous version.
They are not conecting to RF energy batteries ou to cables from other mods, and they used to work along with Thermal Expansion, EnderIO, Mekanism...
If they are going yo use exclusively MJ, well... I don´t think this is a good way to follow...

BuildCraft version: 
Forge version: 
Link to crash report or log: 
Singleplayer or multiplayer: 
Steps to reproduce: 
Additional information:

**Comment by AEnterprise** [comment]
BuildCraft is designed to provide a challenge to players, of which power generation is no exception. RF mods generally remove said challenge, so we brought back MJ in order to encourage players to generate power in more interesting ways.

the creative engine is the most powerfull way, it's output is configurable by shift clicking it with a wrench

**Comment by spitfire1081** [comment]
I don´t see this as a challenge, but for me I see this as the end of the use of this mod in my modpack.
I don´t see showcases of this mod in FTB anymore.
Why? Because MJ sux as energy source.
Sorry to say that, but it´s incompatible with all the other mods in the pack.
Think about that, or at least give the administrators a configuration to allow the use of RF, Tesla, EU as energy sources.

**Comment by AEnterprise** [comment]
it's not in FTB packs because BC is still in alpha, we specifically ask people not to include it in major modpacks, also not all mechanics have been implemented yet

it is suposed to be incompattible with everything else, it's a sepereate energy system, if you realy want to not use it then grab one of the converting mods out there (although i do recomend you give it a chanse, especially later once the mechanics are in place)
