### ISSUE TITLE
Basic gate recipe

### ISSUE THREAD

**Issue by Orygeunik** [BuildCraft/BuildCraft#4092]
BuildCraft version: 7.99.15
Forge version: 14.23.2.2611
Singleplayer or multiplayer: Multiplayer
Steps to reproduce: Set to assembly table red (green) wire and redstone chipset... and basic gate project not shows
Link to recipe:
http://crafting-guide.com/browse/buildcraft/basic_gate/
Link to alternative recipe (and too give no result):
https://ftbwiki.org/Basic_Gate

Pictures for example:
![pic0](https://user-images.githubusercontent.com/6960655/37621140-291339a0-2bcf-11e8-92bc-c49b7e38ed3c.png)
![pic1](https://user-images.githubusercontent.com/6960655/37621205-4f783208-2bcf-11e8-875a-5dd11160fc63.png)
![pic2](https://user-images.githubusercontent.com/6960655/37621259-7644531c-2bcf-11e8-995a-00b7b056b413.png)

For show that assembly table is working:
![pic3](https://user-images.githubusercontent.com/6960655/37621260-76643c9a-2bcf-11e8-8ce7-ebeaf66f536d.png)

Which recipe is correct?

Sorry for bad english :)

**Comment by AEnterprise** [comment]
for the recipes you can check the guide book (non assembly ones will be in JEI as well), gates are in there but not all blocks are atm

those wiki resources are just a bit outdated

**Comment by AlexIIL** [comment]
For reference, here is the first page of gate recipes: (some of them are made in a crafting table rather than the assembly table, although you should check the later pages for the rest of the recipes)
![screenshot from 2018-03-19 20-54-40](https://user-images.githubusercontent.com/3751138/37621823-01fc636c-2bb8-11e8-84c6-ecb2944123dc.png)
