### ISSUE TITLE
Modpack crash on Loading World

### ISSUE THREAD

**Issue by Dastro02** [BuildCraft/BuildCraft#4226]
Hey! Sorry, but I'm not sure if this is the correct forum for my issue but here it goes;

Minecraft Version: 1.7.10
BuildCraft version: 7.1.11
Forge version: 10.13.4.1558
LiteLoader Version: 1.7.10_04
Link to crash report or log: https://pastebin.com/vxJ3v2pB
Singleplayer or multiplayer: Single Player

I'm trying to build my own modpack, but when I try to launch into a single player world, it crashes. I've tried disabling and re-enabling Optifine, FastCraft, BetterFPS, and ThermalFoundation (kept erroring). I don't exactly have an idea of what is causing it to crash. I also tried getting a different version of Optifine to see if that helped but nope. Not quite sure not to do from here.

**Comment by AlexIIL** [comment]
`
Caused by: java.lang.RuntimeException: asm error net.minecraft.client.renderer.texture.TextureMap 8c4787a1 h 0 2
at fastcraft.asm.FastCraftTransformer.transform(F:251)
`
I think fastcraft is crashing for some reason. Can you try temporarily removing all optimising mods (optifine, fastcraft, and betterFPS) and re-running it?

**Comment by Dastro02** [comment]
Okay, it gave me a new crash report. I spotted this while reading through it;
java.lang.VerifyError: Bad local variable type
Here's the new report: https://pastebin.com/aFMzAUAh

**Comment by asiekierka** [comment]
Coremod issue.
