### ISSUE TITLE
Server crash on update version

### ISSUE THREAD

**Issue by moran-x** [BuildCraft/BuildCraft#4326]
BuildCraft version: 7.99.20 to 7.99.21
Forge version: 1.12.2-14.23.5.2768
Link to crash report or log: https://pastebin.com/3SZT76gR
multiplayer: multiplayer
Steps to reproduce:  Update buildcraft from 7.99.20 to 7.99.21
Additional information: ---

**Comment by AlexIIL** [comment]
Yes, but the crash is happening in forestry code so I'm not sure quite what's happening, or why buildcraft could be causing it.

**Comment by AlexIIL** [comment]
Right, I should have looked at the forestry code sooner - it's caused by buildcraft's API name changing, which caused forestries `@Optional` code to break [here](https://github.com/ForestryMC/ForestryMC/blob/4c7273464f66559e1a5bc2dfed0881a1e45dc546/src/main/java/forestry/core/utils/InventoryUtil.java#L89).
