### ISSUE TITLE
Make pipes expose inventory into which you can push items

### ISSUE THREAD

**Issue by roboderpy** [BuildCraft/BuildCraft#4335]
long term request (can be implemented when buildcraft is going to be released)

Make so pipes (or only wooden pipes) expose item capability and when you push into an item into item capability pipe would accept the item

Pipes/move meanings from other mods already work this way (thermal dynamics/immersive engineering/mekanism), so BuildCraft should too (this will take away need in compability between buildcraft and other mods which want to interact with pipes).

Implementation of this capability would allow other mods machinery to push items into pipes without any specific support for buildcraft pipes on their side (so other mods machines can behave like Quarry/Mining Well in meaning of pipes interaction).

**Comment by bookerthegeek** [comment]
I would think not all pipes, maybe just the extraction pies?

**Comment by AlexIIL** [comment]
The only reason why pipes don't currently expose this is because the only item capability in forge is the slot-based `IItemHandler`, and I would need a slot-less "insertion" capability to expose *instead*.

This is only a problem for buildcraft because we have gates with triggers like "Is Inventory Full" and "Is there space for x items", which look for every `IItemHandler` to determine if the inventory is full. However this makes no sense when applied to pipes as they would have to expose a single slot for things to insert into, and then gates would have to special case pipes to ignore them *specifically*.

Instead what all pipes currently do is expose [`IInjectable`](https://github.com/BuildCraft/BuildCraftAPI/blob/8.0.x/api/buildcraft/api/transport/IInjectable.java).

Also I'm not sure how exposing the `IItemHandler` interface only for certain pipe types would be useful, as currently the quarry and mining well don't care what sort of pipe they output to.
