### ISSUE TITLE
Oil spouts do not spawn in superflat worlds

### ISSUE THREAD

**Issue by Rukia1727** [BuildCraft/BuildCraft#4356]
BuildCraft version: 7.1.23
Forge version: 10.13.4.1614
Link to crash report or log: 
Singleplayer or multiplayer:  Singleplayer
Steps to reproduce: Create new world, --> Select Superflat --> Do overworld/desert (I modified desert to have the proper resources to generate ores and other resources and set it to oil field) --> create. No oil at all. 
Additional information: 
I have been trying to get oil to spawn in superflat and it is refusing to spawn any oil at all. I'm testing some tech mods and this is kinda frustrating I cannot get oil to spawn in. This has to be a bug because it is set to biome 127 (desert oil field) and the world is set up exactly like a regular world (~3 layers of sand, ~3 layers of sandstone and ~54 layers of stone) so there should oil wells, especially because I set the probablity in the config to 500 in furiation to not finding any, and no oil

Here is my preset code
2;7,54x1,3x24,3x12;127;,biome_1,decoration,stronghold,mineshaft,dungeon

**Comment by asiekierka** [comment]
This is a quirk - ChunkProviderFlat does not emit the chunk population event we rely on, unlike other chunk providers. Probably because said chunk population generally handles things missing in superflat worlds - ores, lava clusters, et cetera.

As such, I think this behaviour is correct for BuildCraft - oil is a resource, like ores and lava clusters.
