### ISSUE TITLE
Server crash from water filling up in a giant quarry

### ISSUE THREAD

**Issue by Smartjer123** [BuildCraft/BuildCraft#4358]
BuildCraft version: 7.99.21
Forge version: 14.23.5.2811
Link to crash report or log: https://pastebin.com/RDreg3ZA
Singleplayer or multiplayer: multiplayer 
Steps to reproduce: Build a giant quarry and it will up with water causing the server to crash.

**Comment by NocturnalScream** [comment]
A solution would be to place a pump next to the quarry and let the pump drain liquids found within the quarries mining space. I think the quarrysplus mod had that way back in time

**Comment by legoj15** [comment]
It should probably be noted that pumps do not remove water blocks by default, so you need to change a config setting for water to actually be pumped out of the quarry or else you'd be generating water fruitlessly

**Comment by AEnterprise** [comment]
this crash isn't actually caused by buildcraft at all though. buildcraft is only removing blocks, causing water to flow. this is causing block updates to occur as water flows, and some other mod is doing some very heavy computing then, causing the entire server to lag so much the watchdog kills it, nothing we can really do about that
