### ISSUE TITLE
I can't use the Architect Table 7.1.23

### ISSUE THREAD

**Issue by Decanemera** [BuildCraft/BuildCraft#4462]
- Forge Version: 10.13.4.1558-1.7.10
 - BuildCraft Version: 7.1.23

**Comment by AlexIIL** [comment]
Can you be more specific? What have you tried doing, and what is it actually doing?

**Comment by ImSmail** [comment]
I checked it out with a fresh install and it works. However you may need the destroy the architect table and put it in an other corner, since at my first place it didn't recognize the landmarks when I placed it in a right corner. Left corners work well.

```
+-------------------------+
|                         |
|                         |
|                         |
|                         |
|                         |
+-------------------------+
X
```

If you place it where the X is it'll probably work. There was a bug back then in version 1.7.10 and below where quarries and other things didn't recognized the landmarks and didn't place the black and yellow mark lines. You may want to replace all the landmarks before placing the architect table again.
