### ISSUE TITLE
Diamond Pipe doesn't distinguish cables from ic2

### ISSUE THREAD

**Issue by ashlanderr** [BuildCraft/BuildCraft#4553]
- Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2847
 - BuildCraft Version: buildcraft-all-7.99.24.5
 - IndustrialCraft Version: industrialcraft-2-2.8.176-ex112

1. Create a diamond pipe.
2. Attach two cobblestone pipes for output.
3. Attach some pipe for input.
4. In diamond pipe filters, set "Copper Cable" for the first pipe, and "Insulated Copper Cable" for the second.
5. Pass multiple cables into the diamond pipe.

Expected: The "Copper Cable" must go out from the first pipe, and the "Insulated Copper Cable" - from the second pipe. 
Actual: The items choose pipes randomly. 

This also works with "Tin Cable".

**Comment by ashlanderr** [comment]
I think the problem is [here](https://github.com/BuildCraft/BuildCraft/blob/7.99.24.5/common/buildcraft/lib/misc/StackUtil.java#L298).

```java
if (base.getItem() != comparison.getItem()) {
    return false;
}
```

Somehow "Copper Cable" and "Insulated Copper Cable" have the same `stack.getItem()` object.

I've changed the condition, and now it works.

```java
if (!Objects.equals(base.getDisplayName(), comparison.getDisplayName())) {
    return false;
}
```

I know, it's not a good idea to compare items by name, but now we know where is the problem.

**Comment by AlexIIL** [comment]
For some reason ic2 stores insulated cable variants in NBT, rather than in the items metadata or as a different item, however the diamond pipe doesn't filter by NBT - instead you can use a list, and click the `P` button to make it compare items precisely.

We don't filter by NBT by default because NBT is normally used for things with large variance - like written books, or the amount of liquid in a container, etc. For ic2 however it might make sense to compare the specific NBT tags that ic2 uses, as insulated cables should probably be sortable by default. (However that would need to go in compat *somehow* rather than in base BC).

**Comment by ashlanderr** [comment]
Thank you for the reference to a list. It was hard to find any info about the list and its usage with diamond pipes. 

If you don't mind, I want to try to fix the issue. My idea is to add some registry of comparison rules to the StackUtils. Other mods, like BuildCraftCompat, can use this registry to add their own rules. These rules can represent some "common sense comparison", like the difference between insulated and simple cables.

**Comment by AlexIIL** [comment]
Sure!

**Comment by ChangeOtaku** [comment]
what do you guys mean by "list"?

**Comment by AlexIIL** [comment]
I've finally released this fix in [7.99.24.7](https://mod-buildcraft.com/buildcraft-799247.html) - sorry for the delay.

**Comment by AlexIIL** [comment]
ChangeOtaku: A list is an item that contains "ghost" copies of other items, and allows diamond pipes to filter up to 18 items per slot (so up to 162 per side) rather than just 9. It looks like this: 
![image](https://user-images.githubusercontent.com/3751138/95117219-1e256280-0740-11eb-9f06-ab13a9212712.png)

**Comment by ChangeOtaku** [comment]
oh, i´ve never seen this "list item", neither this P-T-M buttons... im playing on 1.12.2
