### ISSUE TITLE
Render Pipe Holder Crash on World Startup

### ISSUE THREAD

**Issue by Dr-Von-Feffarf** [BuildCraft/BuildCraft#4561]
So, I started running a RFTools Builder linked indirectly to a BC pipe system. It ran fine until this morning, when my game started crashing on loadup, yielding a "render.RenderPipeHolder" error. I'm using MC 1.12.2, BC version 7.99.24.6. I was previously using 7.99.24.4, and updating the mod gave me an extra second before the crash occurs.

Crash Log:
https://gist.github.com/Dr-Von-Feffarf/3130e79fb9ad321a65f5c2bf894f1d32

**Comment by Dr-Von-Feffarf** [comment]
Hey, is this being worked on? I don't mean to be impatient or disrespectful, it's just that I haven't been able to play for more than a week, and I'd like to know if there's an ETA, or if there's anything I should try in the meantime.

**Comment by AlexIIL** [comment]
Sorry, I should have commented before :/

This is most likely a bug with forestry, however as it's not possible for us to tell which item is causing this I'm going to push a prerelease to help diagnose this.

**Comment by Dr-Von-Feffarf** [comment]
Okay, sounds good! Any idea when it's going to be available for download?

**Comment by AlexIIL** [comment]
Now, from the [tests page](https://mod-buildcraft.com/pages/tests.html) (direct link to [7.99.24.7-pre.2](https://mod-buildcraft.com/releases/testing/BuildCraft/7.99.24.7-pre.2/buildcraft-all-7.99.24.7-pre.2.jar))

**Comment by Dr-Von-Feffarf** [comment]
Okay, so just download that, reproduce the crash, then upload it here?

**Comment by AlexIIL** [comment]
Yes please!

**Comment by Dr-Von-Feffarf** [comment]
Done:
https://gist.github.com/Dr-Von-Feffarf/e4cae725d9d492eadad71ee4091f99bd

**Comment by AlexIIL** [comment]
Ok, thanks.

I used `/give AlexIIL forestry:leaves.default.fruit.0` and I also crashed (this time due to rendering the item as an entity) so I don't think there's much more I can do here - ~~you'd be better off opening an issue on forestry's github: ~~ Turns out they already know (https://github.com/ForestryMC/ForestryMC/issues/2336) and so the fix is to update forestry to the latest version (although I think you'll have to download the latest *beta* release instead).

**Comment by Dr-Von-Feffarf** [comment]
Ayyyyyy, it works! Thanks  so much for the help!
