### ISSUE TITLE
Diamond pipe suggestions

### ISSUE THREAD

**Issue by josh-65** [BuildCraft/BuildCraft#4579]
**Is your feature request related to a problem? Please describe.**
First one is empty diamond pipe place together. when this happens putting a stack of a block then having it go through the pipe it will split it. So rather then putting the whole stack in the first available chest it does 32, 16, 8, 4, 2 and 1 amounts in different chests.

**Describe the solution you'd like**
Second is being able to change the coloured slots to have more than 9 items allowed to be sorted. Maybe this can be done with dye or a colour picker to change the whole row to that output colour.

**Comment by AlexIIL** [comment]
1: This is the current behaviour, and it's intentional - unlike all other pipes it splits stacks up into the available directions, which means it always splits evenly if the stack amount is divisible by . For "Always insert into the first available chest" you can use a clay pipe, which is the only BC pipe with that behaviour.

2: You can use a list for this - lists have 18 slots to filter items (in their default mode) and only take up a single slot in the diamond pipe GUI, which allows for up to 162 items per side.

**Comment by josh-65** [comment]
Ok thanks.
