### ISSUE TITLE
(1.12.2) Refinery and Heat-Exchanger does not accept Crude Oil from Thermal Foundation

### ISSUE THREAD

**Issue by Gitcrafter** [BuildCraft/BuildCraft#4660]
The Refinery and Heat-Exchanger do not accept the Crude Oil from Thermal Foundation, but they do accept the Crude Oil from Galacticraft on the other hand
It´s either a Bug or inconsistent modsupport

 - Forge: 1.12.2-14.23.5.2859
 - BuildCraft: 1.12.2-7.99.24.8
 - Thermal Foundation: 1.12.2-2.6.7.1
 - Galacticraft: 1.12.2-4.0.2.281

**Comment by AlexIIL** [comment]
BuildCraft doesn't have any specific compatibility code with either Galacticraft or Thermal foundation, so this isn't caused by us.

I think this is because of how forge's fluid system works: buildcraft uses the fluid name "oil" for oil, and galacticraft does too - so they are considered the same fluid by all of buildcraft. Thermal Foundation probably uses something like "crude_oil", so it's different.

**Comment by Gitcrafter** [comment]
So, is there a way to make it compatible?

**Comment by Primitive-Human** [comment]
Change the worldgen and recipes of Thermal Foundation and Thermal Expansion to give buildcraft's oil instead of its own crude oil fluid.

**Comment by Gitcrafter** [comment]
And how the hell am I supposed to know how I have to do that?

**Comment by Primitive-Human** [comment]
Worldgen: Go to your .minecraft/config/cofh/world folder for the Thermal Foundation worldgen files. 

For the recipes you could use CraftTweaker and Modtweaker. You'll mostly have to edit the Magma Crucible recipes that extracts  crude_oil from Thermal Foundation's bitumen and oilsands. 

That's more than enough handholding. There's no way to add recipes to Buildcraft's heat exchanger or refinery, so the only possible compatibility is to make TE/TF produce and use BC oil only, which is 100% doable.

**Comment by Gitcrafter** [comment]
so as a test I made this:
I tried to add a recipe to TE´s centrifuge to turn 1x bitumen into 300 mB oil and 1x tar with 10% chance using 2000 RF, but it isn´t working

the file is named:
mods.thermalexpansion.Centrifuge.zs and is a .txt file and located in the scripts folder

the script is:
//mods.thermalexpansion.Centrifuge.addRecipe(WeightedItemStack[] outputs, IItemStack input, ILiquidStack fluid, int energy);
mods.thermalexpansion.Centrifuge.addRecipe([<thermalfoundation:material:833> % 10], <thermalfoundation:material:892>, <liquid:oil> * 300, 2000);

**Comment by Primitive-Human** [comment]
Rename the text file to just thermalexpansion_compatibility.zs. Make sure it's an actual .zs file, and not .txt, so it shouldn't be "thermalexpansion_compatibility.zs.txt",  because CraftTweaker won't read that.

Second: Your recipe won't work because you need to have a basic understanding in CraftTweaker.
The correct script for your recipe would be:


```
import mods.thermalexpansion.Centrifuge;
mods.thermalexpansion.Centrifuge.addRecipe([(<thermalfoundation:material:833>)] % 10,  <thermalfoundation:material:892>, <liquid:oil>*300, 2000);
```

Items and liquids need to be put between <...> . Also make sure you installed ModTweaker, as CraftTweaker on its own cannot modify ThermalExpansion recipes in 1.12.2.

**Comment by Gitcrafter** [comment]
thanks for the quick answer, but how can I make a .zs file? and yes I have both CraftTweaker AND ModTweaker

**Comment by Primitive-Human** [comment]
Open the .txt file in your text editor (I use Notepad++). Then, use "save as". In the box where you typ the name of the new to be saved file you can save it as somethingsomething.zs .

**Comment by Gitcrafter** [comment]
You helped me so much, Thank you!!!
